### ISSUE TITLE
Writing a custom (async) source?

### ISSUE THREAD

**Issue by HiPhish** [nvim-lua/completion-nvim#119]
Hello,

I have been toying with the built-in LSP and your completion plugin looks at the moment like the best-integrated completion framework. I have been using [ncm2](https://github.com/ncm2/ncm2) until now, and I even wrote [an asynchronous source](https://github.com/HiPhish/ncm2-vlime) for [Vlime](https://github.com/vlime/vlime).

My question is: is it possible to write new asynchronous sources, or is this plugin limited to asynchronous LSP only? There is nothing about custom sources in the documentation, but a quick look at the source makes it look as if it is possible to define at least new synchronous sources. It would be nice if there was documentation, and perhaps even a little toy example like completing days of the week if it is not too much work. I am pretty decent at writing, so if you can help me understand the API I can offer to help write the documentation.

**Comment by haorenW1025** [comment]
Sorry for the late replied, I've been very busy this couple of weeks. Writing an async source is definitely possible, one example is the built-in path completion in `lua/source/path.lua`. Basically you have to give a boolean value `M.callback` to completion-nvim, if the async procedure is done you have to raise the callback to true. I'll give a basic example in wiki when I have some spare time.

**Comment by HiPhish** [comment]
Thank you for the response. What I mostly need to know is what keys there need to be in a source table, what their meaning is, and how they fit into the bigger picture. I see that `path` and `lsp` have three keys (`triggerFunction`, `getCompletionItems`, `getCallback` and `callback`), `snippet` has only one (`getCompletionItems`) and `ins_complete` has a different one `triggerCompletion`.

**Comment by haorenW1025** [comment]
That's the main difference between async and sync sources. `completion-nvim` call `getCallback` to get the callback boolean value to make sure if the async procedure is done. `triggerFunction` basically trigger the async procedure and after `getCallback` is true completion-nvim will call `getCompletionItems` to get all the items and display it in complete menus.  Also `ins_complete` have to use a totally different approach so you shouldn't need to look into that. Not sure if this explain is clear enough.. Feel free to ask anything question if you have further question!

**Comment by HiPhish** [comment]
I think I am starting to understand: the entry point is `triggerFunction`, it does its work in preparing for completion, sets the `callback` value to `false`, and then it terminates. After a while, through whatever magic means, the `callback` value is set to `true`, which will then trigger calling the `getCompletionItems` function. That function resets `callback` back to `false` and returns a list of completions items according to the specification in `:h complete-items`. Correct so far?

That would mean that the flipping over of `callback` to `true` is the signal that tells completion-nvim that it can pick up the completion items. There are other keys in the source tables (`M.items`, `M.getCallback`, `M.keyword`), are they relevant as well? If yes, what do they do? If not, why are they being exposed to the outside world instead of being local to the module?

If I find the time I'll try my hand at creating an asynchronous Vlime source over the weekend.

**Comment by haorenW1025** [comment]
You're correct on most of the things! Some key was not very well implemented on my side though. So actually `M.callback` can be stored as a local variable, you just need a `M.getCallback` function to get this value. Same case for `M.items`, you should be fine using that as a local variable too. `M.keyword` is use to handle special case in path completion so it should be irrelevant for you.
Great to hear you trying to write some sources! If you manage to create it please let me know, I can put it in README in case if others want to use similar things!

**Comment by HiPhish** [comment]
Here is a little toy source I cam up with:

```lua
function M.getCallback(args)
	return callback
end

function M.getCompletionItems(args)
	callback = false
	return {"aaaa", "aaab", "aaabbaa", "bbbbaaaa", "bbbccc",
	".aaaa", ".aaab", ".aaabbaa", ".bbbbaaaa", ".bbbccc",
	}
end

function M.triggerFunction(prefix, _, bufnr, _)
	callback = true
end
```

It's not particularly asynchronous because it immediately sets `callback` to true, but I'm just trying to make something work here. I still need to register the source, so I added this to my `init.lua`:

```lua
local completion = require 'completion'
local vlime = require 'completion_nvim.source.vlime'
completion.addCompletionSource('vlime', {
    trigger = vlime.triggerFunction,
    callback = vlime.getCallback,
    item = vlime.getCompletionItems,
})
```

Now when I open a new Neovim instance and start typing `aaa` nothing happens, even though I expected to see the first three items as suggestions. What have I done wrong here? Also, which areguments are passed to `triggerFunction`? I have seen different sources with different signatures.

**Comment by HiPhish** [comment]
Never mind, I made a mistake, the items are not supposed to be literal strings, but tables.

```lua
function M.getCompletionItems(args)
	-- callback = false
	-- return items
	callback = false
	return {
		{word = "aaaa"},
		{word = "aaab"},
		{word = "aaabbaa"},
		{word = "bbbbaaaa"},
		{word = "bbbccc"},
		{word = ".aaaa"},
		{word = ".aaab"},
		{word = ".aaabbaa"},
		{word = ".bbbbaaaa"},
		{word = ".bbbccc"},
	}
end
```

And I needed to add it to the chain completion list. Now I can try integrating this with Vlime to get a useful source :)

**Comment by haorenW1025** [comment]
I think you can look at `complete.lua` for stuff passing into `triggerFunction`, the triggerFunction for path completion is different because it's kind of different..

**Comment by HiPhish** [comment]
I got it working.
![Screenshot_20200628_161314](https://user-images.githubusercontent.com/4954650/85950012-6f140680-b95a-11ea-9c64-1ed1bfaefe02.png)

The only problem is that the items are ordered alphabetically, but that's not related to the source. I guess I could do some more filtering using the current prefix as the criterion.

**Comment by haorenW1025** [comment]
Actually I've got a matching function which will match your word to prefix according to a user defined strategy. Currently you can use `require 'completion.matching'.match` to call this function(See function `text_document_completion_list_to_complete_items` in `lsp.lua` for reference). However I should put this function in `completion.lua` to let you use `require 'completion'` instead of `require 'completion.matchin'`.

**Comment by HiPhish** [comment]
I'm done, here is the Vlime source: https://gitlab.com/HiPhish/completion-nvim-vlime ([GitHub mirror](https://github.com/HiPhish/completion-nvim-vlime)).

**Comment by haorenW1025** [comment]
Nice! However I'm introducing some changes on the triggerFunction in #132 cause things that are passed in is very messy. Right now I want it to be `triggerFunction(manager, option)` where manager is a generic manager table in `completion.lua` and option is a table with stuff you may need in completion stage, like bufnr, prefix and some stuff, so you should be able to get prefix by `option.prefix`. I think it's easier because otherwise I'll try passing in different stuff for different sources and it is confusing. Will notice you when merging that PR.

**Comment by HiPhish** [comment]
Did you change how completion items are sorted? Previously they were sorted alphabetically without regards to what was being completed, but now I get a really sensible ordering. I like it.
![Screenshot_20200702_221327](https://user-images.githubusercontent.com/4954650/86405214-49b42f00-bcb1-11ea-9499-3a275fae9155.png)

**Comment by haorenW1025** [comment]
If you use the matching stuff you should have good sorting because I handle that on my side. I'll send you a PR on github later to fix that. Also I'll change some stuff to for the incompatible changes.

**Comment by haorenW1025** [comment]
I'm closing this now. Be aware of the async sources api is not very stable, we might have changes to it in the future. I'll make sure you're mentioned if we changes some stuff though. Feel free to ask me if you have any problems:)

**Comment by HiPhish** [comment]
One more question: what does the `match.matching` function do? I looked at the source and it seems like a filter and a map: it filters out completion items which do not match any of the strategies from `g:completion_matching_strategy_list`, and it maps each item to another item which has missing tables entries filled in with some default value. Is that correct?

> Be aware of the async sources api is not very stable, we might have changes to it in the future.

Then there is no point in documenting how to write sources currently?
