### ISSUE TITLE
Move `source` into a subdirectory?

### ISSUE THREAD

**Issue by HiPhish** [nvim-lua/completion-nvim#120]
While looking at the source code I noticed that the `source` module is a top-level Lua module. By that I mean that both the `source.lua` file and the `source` directory are right in the `/lua/` directory. If another plugin or a users wants to use the `source` name, then they will be stepping on this plugin's toes. For example, let's say I have a file named `~/.config/nvim/lua/source.lua`, which one will this plugin load?

I know some other plugins are already using the `source` module, but in my opinion it's better to have a small and easy to fix breakage now, than to have a bigger break later down the road. Or am I mistaken on this one?

**Comment by haorenW1025** [comment]
Yeah I should definitely move that. By the time I started this plugin I didn't have the sense of conflicting names.. I would start working on that. Thanks for the report:)

**Comment by haorenW1025** [comment]
Done moving, close this now, thanks again!

**Comment by HiPhish** [comment]
I think you misunderstood me. I did not mean just the `source.lua` file, but the entire directory structure. Instead of this:

```
lua
├── completion
│   ├── chain_completion.lua
│   ├── complete.lua
│   ├── health.lua
│   ├── hover.lua
│   ├── matching.lua
│   ├── signature_help.lua
│   └── util.lua
├── completion.lua
└── source
    ├── ins_complete.lua
    ├── lsp.lua
    ├── path.lua
    ├── source.lua
    └── snippet.lua
```

I meant this:

```
lua
└── completion
    ├── chain_completion.lua
    ├── complete.lua
    ├── health.lua
    ├── hover.lua
    ├── matching.lua
    ├── signature_help.lua
    ├── source
    │   ├── ins_complete.lua
    │   ├── lsp.lua
    │   ├── path.lua
    │   └── snippet.lua
    ├── source.lua
    └── util.lua
```

The way you have it now, if another plugin (or a user's `~/.config/nvim`) also has a file `lua/source/path.lua` there will still be a name collision. Moving *all* your files into one sub-directory means there cannot be a collision unless another plugin is also called `completion`, and if that happens it's their fault.

Old Vim script plugins could run into the same problem if they used the same names in autoload file names. If my plugin has an `autoload/foo.vim` and your plugin has an `autoload/foo.vim`, whose file should be sourced to call `foo#bar()`?

**Comment by haorenW1025** [comment]
Oh yep that's actually better. But it should be way easier now cause there will be no backward compatible issue with all the wrapper stuff I create. I'll work on that:)

**Comment by HiPhish** [comment]
BTW, note that I placed the `source.lua` file outside the `source` directory. It's nicer to write `require 'completion.source'` than `require 'completion.source.source'`. This is closer to how you had set up the directory structure originally.
