### ISSUE TITLE
Allow multiple snippet sources

### ISSUE THREAD

**Issue by Iron-E** [nvim-lua/completion-nvim#122]
**Is your feature request related to a problem? Please describe.**

Before beginning the transition to using Neovim 0.5 and its LSP support, I used `coc.nvim` (like many others). `coc.nvim` has a plugin called `coc-snippets` which allows you to source snippets from multiple locations (such as honza/vim-snippets).

However, this plugin only allows the declaration of one source at a time:

```viml
let g:completion_enable_snippet = 'vim-vsnip'
```

**Describe the solution you'd like**

It would be convenient to allow the assigning of a list of completion sources.

This would also make future supported sources (if any) more easy to implement into a personal configuration, as one wouldn't have to give up their other sources:

```viml
let g:completion_enable_snippet = ['Neosnippet', 'vim-vsnip']
```

**Describe alternatives you've considered**

Another solution would be to define another snippet provider through fallback completion:

```viml
let g:completion_chain_complete_list = [
\	{'complete_items': ['lsp', 'snippet', 'Neosnippet']},
\	{'mode': '<c-p>'},
\	{'mode': '<c-n>'}
\]
```

Here, `'snippet'` would act as a stand-in for whatever `g:completion_enable_snippet` is set to.

**Comment by haorenW1025** [comment]
Hmm I think the second approach you mention is better cause it doesn’t break backward compatibility and should be quite easy to implement. I’ll look into it.

**Comment by haorenW1025** [comment]
You can try #129 and it should be working.

**Comment by haorenW1025** [comment]
Close by #129.

**Comment by Iron-E** [comment]
Sorry for the late response, this works great! I appreciate it.
