### ISSUE TITLE
score_func in path.lua is sometimes nil

### ISSUE THREAD

**Issue by wbthomason** [nvim-lua/completion-nvim#131]
**My testing minimal init.vim**
Default configuration, making sure the `path` source is configured to be used.

**How to reproduce**
Try typing in a context that should trigger the `path` source. Note that you get errors complaining that in `path.lua` line 39, there's an attempt to call `score_func`, which is `nil`.

**Expected behavior**
The `path` source returns without errors.

**Comment by haorenW1025** [comment]
Should be fix now, please update and check:)

**Comment by wbthomason** [comment]
Seems to be fixed, thanks!
