### ISSUE TITLE
Using `let g:completion_auto_change_source = 1` causes strange pop up behavior

### ISSUE THREAD

**Issue by kdheepak** [nvim-lua/completion-nvim#134]
When the first character triggers the completion it results it the pop up appearing and disappearing. After typing the second character everything behaves as expected.

![completion-nvim-bug mov](https://user-images.githubusercontent.com/1813121/86500445-4e7af080-bd4e-11ea-9eba-8e533f8f30eb.gif)

I wasn't able to get this to work with a MINRC. Also this feature is not documented so I'm just not going to use it for now. This is the change in the vimrc that I had to make to get it to behave normally again:

https://github.com/kdheepak/dotfiles/commit/87bf3b380ee323dc08d45c812e1e7d0ce4e99b21

You can see the commit there for a fully reproducible example if you like.

**Comment by haorenW1025** [comment]
I can reproduce, will try to solve this.

**Comment by haorenW1025** [comment]
Can you try #139 and see if it works?

**Comment by kdheepak** [comment]
Works for me! Thanks for the quick fix!

**Comment by haorenW1025** [comment]
Merged!

**Comment by kdheepak** [comment]
Thank you!
