### ISSUE TITLE
Caching mechanism not working with fuzzy matching

### ISSUE THREAD

**Issue by clason** [nvim-lua/completion-nvim#137]
The recent commit https://github.com/nvim-lua/completion-nvim/commit/994450afc8b4006e2043d5944b2ca51b1c23c9aa introduced a regression where completion candidates are missing when the `fuzzy` matcher is used (among others). If the cache is manually cleared at the start of `performComplete`, the expected list of candidates is again shown. The behavior is better but not completely fixed if only `exact` matching is used.

(Quick manual workaround if others hit this: add `cache_complete_items = {}` in line 36 of `complete.lua`.)

**Comment by haorenW1025** [comment]
I'll try solving this in #138.

**Comment by clason** [comment]
Thank you!
