### ISSUE TITLE
Completion exits to normal mode

### ISSUE THREAD

**Issue by loshjawrence** [nvim-lua/completion-nvim#142]
Completion always exits to normal mode (using no overrides or overrides suggested in the README). Is this expected?

**Comment by haorenW1025** [comment]
I don't get what you means when you say exits to normal mode. Can you provide more detail information of a gif to explain what you mean?

**Comment by loshjawrence** [comment]
Like if i tab or c-n down to a item in the completion list then hit enter or escape (or whatever the completion trigger is setup to be) it wont stay in insert mode and instead goes to normal mode.

**Comment by loshjawrence** [comment]
Actually its probably something in my .vimrc that's interfering since https://github.com/nvim-lua/completion-nvim/issues/143 has a minimal vimrc that seems to not be hitting my issue.
