### ISSUE TITLE
How to deduplicate items provided by different sources?

### ISSUE THREAD

**Issue by m00qek** [nvim-lua/completion-nvim#152]
Hey, thank you for this plugin, it is being really useful to me.

I created a new completion source named [conjure](https://github.com/m00qek/completion-conjure) and I'm using it like this:

```vim
let g:completion_chain_complete_list = {
\ 'clojure': [
\   {'complete_items': ['conjure', 'lsp', 'snippet']},
\ ]
\}
```

It is working fine but `lsp` and `conjure` sometimes bring the same suggestion, appearing as a duplicate in the completion list.
In this case, what I want to do is to show the item from `conjure` because it has better information (kind, etc.)... is there any known way to filter the results of many sources? Could you please give me any direction?

Thanks!

**Comment by haorenW1025** [comment]
According to `:h complete-items`, if should specify items as `dup = 0` it would be filter out. However I'm handling this in `util.addCompletionItems` now so this is not configurable currently. Maybe I should somehow make it configurable by adding a variable to handle it.

**Comment by kristijanhusak** [comment]
I'm having the same issue with my dadbod completion. Omnifunc properly filters it out, but completion-nvim leaves the duplicates.

**Comment by kristijanhusak** [comment]
@haorenW1025 setting dup to 0 here https://github.com/nvim-lua/completion-nvim/blob/master/lua/completion/util.lua#L44 makes everything work fine.
For what reason you need to have it as 1?

**Comment by haorenW1025** [comment]
Hmm I was afraid of the order of overwriting. For example, if I set snippets items and LSP items both to 0, I'm not sure which will be deduplicate. Making it customizable for different sources should be a better fix. I'm very busy recently and doesn't have much time working on this but PR is welcome.

**Comment by kristijanhusak** [comment]
@m00qek make sure to explicitly pass down `dup = 0` when generating your complete items, and it will not be duplicated.

**Comment by nabezokodaikon** [comment]
How should I set it specifically?
There is a lot of duplication in LSP.
