### ISSUE TITLE
Allow to configure filetypes where to disable completion

### ISSUE THREAD

**Issue by weilbith** [nvim-lua/completion-nvim#155]
I enabled this plugin for all buffers where lsp is enabled according to the docs. But for some reason this still triggers path completion (which I have in my default sources) when I'm in a special buffer of a plugin. In exact in the filter buffer of the [denite.nvim](https://github.com/Shougo/denite.nvim) plugin. I actually don't know why. So I solved this know by using this configuration:

```vim
let g:completion_chain_complete_list = {
      \   'default': {
      \     ...
      \   },
      \   ... ,
      \   'denite-filter': {
      \     'default': []
      \   }
      \ }

```

**Describe the solution you'd like**

I wonder if it would not be nice to have the option to enable this plugin everywhere **but** exclude a specific list of filetypes. Something stupid simple like `let g:completion_disable_filetypes = ['denite-filter', ...]`. So far I need this only for this single case. But I would be annoyed if I have to copy paste and bloat my configuration for each filetype I want to ignore.

**Describe alternatives you've considered**

Well the configuration I posted above. :wink: 

Thanks for your help!

**Comment by haorenW1025** [comment]
Please try the PR and see if it works😉

**Comment by weilbith** [comment]
Thanks for your blazing fast solution approach. Feedback in the PR. :upside_down_face:
