### ISSUE TITLE
nil error when executing additional text edits

### ISSUE THREAD

**Issue by Kazy** [nvim-lua/completion-nvim#157]
When using `metals`, accepting a completion item can include `additionalTextEdits` to import the selected item. I'm using the same mapping for `<CR>` as in the README (i.e. with `<Plug>(completion_confirm_completion)`). Recently, the feature broke when accepting the completion with the following error:
```
Error detected while processing CompleteDone Autocommands for "<buffer=1>":
E5108: Error executing lua .../.config/nvim/plugged/completion-nvim/lua/completion.lua:87: attempt to perform arithmetic on upvalue 'lnum' (a nil value)
```

I traced it back to commit 8aecb23b5421fa3fdd34a92b2b595ce29b85b82a, more precisely [here](https://github.com/nvim-lua/completion-nvim/commit/8aecb23b5421fa3fdd34a92b2b595ce29b85b82a#diff-9882b35275f8076a05744bbeebe43c04L55), which changed this
```lua
local lnum, _ = unpack(api.nvim_win_get_cursor(0))`
```

into

```lua
local lnum = api.nvim_win_get_cursor(0)[0]
```

Apparently this isn't equivalent. Reverting back this single line fixes the issue. Sorry for the missing reproduction, let me know if one is necessary. Thanks !

**Comment by td0m** [comment]
I believe this is because array indexes start with `1` in Lua:

Reverting back to the original (as stated by Kazy) or changing it to the following code fixes the issue:
```lua
local lnum = api.nvim_win_get_cursor(0)[1]
```

**Comment by haorenW1025** [comment]
Ah that was a bad written code...Should be fixed now.

**Comment by Kazy** [comment]
Perfect, thank you !
