### ISSUE TITLE
Ability to set source precedence

### ISSUE THREAD

**Issue by kuator** [nvim-lua/completion-nvim#164]
**Is your feature request related to a problem? Please describe.**
Completion-nvim allows to sort completion items by length, alphabetical order, but it doesn't allow sort items by their source. 
**Describe the solution you'd like**
Deoplete has this feature which allows to set each source precedence.
https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L1196
**Describe alternatives you've considered**
I tried to put sources into diffeerent `complete_items` in `g:complete_chain_complete_list`. But it's uncomfortable to constantly switch sources.

**Comment by aca** [comment]
@kuator there's already precedence opt by source. I can't find a document for it. But it exists.
```
  let g:completion_items_priority = {
          \ 'Field': 5,
          \ 'Function': 7,
          \ 'Variables': 7,
          \ 'Method': 10,
          \ 'Interfaces': 5,
          \ 'Constant': 5,
          \ 'Class': 5,
          \ 'Keyword': 4,
          \ 'UltiSnips' : 1,
          \ 'vim-vsnip' : 0,
          \ 'Buffers' : 1,
          \ 'TabNine' : 0,
          \ 'File' : 0,
          \}
```
But I also think precedence by sources would be great. There's should be more discussion about it, as It might get really complicated.

**Comment by kuator** [comment]
@aca this is epic, thanks!
