### ISSUE TITLE
Floating window instead of another buffer on the top

### ISSUE THREAD

**Issue by p00f** [nvim-lua/completion-nvim#165]
Hi, I want floating window for signature help (as shown in readme). But I get another buffer on the top:
![Screenshot from 2020-08-03 09-53-24](https://user-images.githubusercontent.com/36493671/89147120-6d4dec00-d573-11ea-9451-62b2ed416ce7.png)

**Comment by Shougo** [comment]
`set completeopt-=preview`

**Comment by PitcherTear22** [comment]
that still doesnt give me the floating window, do i need https://github.com/ncm2/float-preview.nvim ?

**Comment by PitcherTear22** [comment]
Also it would be nice to get syntax highlighting of the signature help (it looks like it is not being treated as monospace
for example in github/other webistes' markdown,
![111](https://user-images.githubusercontent.com/36493671/89152289-7b563980-d580-11ea-9191-885adcdcd5af.png)
is rendered as
```java
if (condtion) {

} else {

}
```

**Comment by astier** [comment]
Its offtopic but what plugin are you my friend @p00f using to display the buffers where usually the tabline resides? Thanks.

**Comment by p00f** [comment]
> Its offtopic but what plugin are you my friend @p00f using to display the buffers where usually the tabline resides? Thanks.

https://github.com/Akin909/nvim-bufferline.lua

**Comment by p00f** [comment]
> that just removes the extra preview buffer and still doesn't give me the floating window, do I need https://github.com/ncm2/float-preview.nvim ?

I installed this and got floating window working
