### ISSUE TITLE
How to not display function-parameters in the completion-menu

### ISSUE THREAD

**Issue by astier** [nvim-lua/completion-nvim#166]
When functions occur in the completion menu then also their parameters are displayed right beside them. Is it possible to just show the function-name without the parameters? Thank you.

![2020-08-04-011437_324x49_scrot](https://user-images.githubusercontent.com/36510152/89236473-ee979400-d5f0-11ea-809d-74a1c4421200.png)

In the screenshot we can see the function `format(o, format_spec)`. I want it to be just `format`

**Comment by haorenW1025** [comment]
That's the default behavior since completion-nvim doesn't do extra things besides handle the message coming from language server. You might want to seek if there are option in your lsp in `nvim-lsp` repo of the `available section` to disable it.
