### ISSUE TITLE
Sort matches accoding to length desc

### ISSUE THREAD

**Issue by mangelozzi** [nvim-lua/completion-nvim#168]
Firstly this completion is so fast, really love it, good work guys.

**Is your feature request related to a problem? Please describe.**
One can sort by length, however it currently shows the shortest first. Generally you want autocomplete for longer suggestions because those are the harder to type correctly.

**Describe the solution you'd like**
Add an option for sorting via length descending. I.e. Longer words shown first.

**Describe alternatives you've considered**
Pressing `i_^p` and cycling backwards through the list.

**Comment by haorenW1025** [comment]
Thanks for the compliment and really sorry for the long wait. I'm the main maintainer of `completion-nvim` and I've been quite busy for the past several weeks. Will start working on this issue!

**Comment by haorenW1025** [comment]
Now you can specify `g:completion_sorting = length_desc` to get sorting via length descending.

**Comment by mangelozzi** [comment]
@haorenW1025 Thanks so much! It be great!
