### ISSUE TITLE
vim-vsnip stopped working from latest udpate

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-lua/completion-nvim#169]
vim-vsnip added support for using same snippet files for multiple filetypes (https://github.com/hrsh7th/vim-vsnip/pull/89). This PR causes snippet autocompletion to not return results any more.

**Comment by hrsh7th** [comment]
Ah!! Sorry, It's my bad...
I will create PR.

**Comment by kristijanhusak** [comment]
@hrsh7th i'll create PR with fix here, no need to change.

**Comment by kristijanhusak** [comment]
@hrsh7th or if you think this will break some other plugins also, they let's keep it backward compatible.

**Comment by hrsh7th** [comment]
I missed the `vsnip#source#find` used in other plugins.
The breaking change does not mean this... sorry.

**Comment by hrsh7th** [comment]
Anyway, thank you for planning to fix it!
