### ISSUE TITLE
How to make cursor go inside brackets after completion, but not after them?

### ISSUE THREAD

**Issue by tooSadman** [nvim-lua/completion-nvim#175]
Hi folks,
there's one thing that annoys me: after completion is done and, for example, it was a function, cursor goes after the parentheses, while I want the cursor to be inside the brackets after completion. 
Could you please suggest what I should do to get the wanted completion behavior?

**Comment by Xuyuanp** [comment]
It's also annoying me for a long time.
Finally, `vim-vsnip` saves my life.

**Comment by haorenW1025** [comment]
`completion-nvim` doesn't handle that very well, because it just display the completion coming from the language server, if you want the expansion to work better, just like @Xuyuanp said, `vim-vsnip` works perfectly with completion-nvim and doesn't need additional setup.

**Comment by tooSadman** [comment]
Yeah, it really works! Thank you guys for help)

**Comment by Xuyuanp** [comment]
@tooSadman config below also works if you are using `gopls`
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = false

nvim_lsp.gopls.setup{
    on_attach = on_attach,
    capabilities = capabilities,
}
```
