### ISSUE TITLE
Disable "default" snippets

### ISSUE THREAD

**Issue by Kyle-Thompson** [nvim-lua/completion-nvim#178]
I have no snippets set up at the moment. :checkhealth reports I haven't set up a snippet source. Yet when I try to edit Rust code I'm given a couple default snippets that aren't very helpful to me that I don't know how to disable. For instance, `call`, `box`, etc, which just expand to a function call or a `Box::new(expr)`. How do I disable these? Where are they even coming from?

**Comment by haorenW1025** [comment]
These snippets came from LSP itself casue language server have snippet support. If you want it to be more usable consider using `vim-vsnip` and `vim-vsnip-integ` together with `completion-nvim`. If you don't maybe you'll need to disable snippets of the LSP side. For ex:
```
require'nvim_lsp'.vimls.setup{
  on_attach = on_attach;
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = false
        }
      }
    }
  },
}
```
If this doesn't help, you may have to look for the `available setting` section on `nvim-lsp`

**Comment by clason** [comment]
See also https://github.com/neovim/neovim/issues/12795

**Comment by Kyle-Thompson** [comment]
Thanks @haorenW1025, that did it!
