### ISSUE TITLE
Typing a new character throws an error when auto-completion gets called

### ISSUE THREAD

**Issue by tr0b** [nvim-lua/completion-nvim#182]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue

aesthetics.vim:
https://pastebin.com/p5eDf1ZE
general.vim:
https://pastebin.com/aCvdEmSs
mapped.vim:
https://pastebin.com/PVry35Dt
initial_plugins.vim:
https://pastebin.com/SBYT7pjf
lsp_config.vim:
https://pastebin.com/PekTjkRE
init.vim:
https://pastebin.com/jxb5gcK6

**How to reproduce**
Detailed step to reproduce this issue.
-Load all .vim config files
-With any of the following Lsp servers:  sumneko_lua, tsserver, vimls, jsonls
-open a correspondent *.ts , *.lua, *.vim, *.js, or *.json file
-type a new character in a new line
-completion nvim will attempt to trigger, but fail with the following error:
![image](https://user-images.githubusercontent.com/60306480/91626894-28e61e00-e970-11ea-99fd-1e1b75c8f994.png)

**Expected behavior**
The expected behaviour should be: No errors should be thrown from completion-nvim when typing new characters.
Surprisingly, this does not seem to happen at all with *.vim files.

**Comment by haorenW1025** [comment]
I can't reproduce on my side though. Have you updated completion-nvim to the latest master branch?

**Comment by hrsh7th** [comment]
I guess it seems caused by old nvim.

**Comment by haorenW1025** [comment]
@hrsh7th Ahh you're right I remember that. @tr0b consider update your neovim to the latest master.

**Comment by tr0b** [comment]
@haorenW1025 Oh, I haven't updated neovim in a while. I will try updating it!

**Comment by tr0b** [comment]
![image](https://user-images.githubusercontent.com/60306480/91642177-68e7e800-e9e6-11ea-93db-e0d292613af6.png)
Seems like updating neovim to the latest nightly release and updating completion nvim fixed the problem. Thank you @haorenW1025 and @hrsh7th !
