### ISSUE TITLE
Preview markdown contains whitespace

### ISSUE THREAD

**Issue by archseer** [nvim-lua/completion-nvim#184]
The signature preview window is styled via vim's syntax highlighting which will highlight trailing whitespace:

<img width="276" alt="Screenshot 2020-09-01 at 00 48 52" src="https://user-images.githubusercontent.com/1372918/91739470-e8df9f00-ebec-11ea-8143-5f295f485519.png">

You can see the same problem with the preview window in the animated demo: Empty lines contain whitespace so they're highlighted.

<img width="570" alt="Screenshot 2020-09-01 at 00 47 41" src="https://user-images.githubusercontent.com/1372918/91739533-014fb980-ebed-11ea-936d-80cc9173efad.png">

I think the problem is that the whitespace is first trimmed away

https://github.com/nvim-lua/completion-nvim/blob/8aecb23b5421fa3fdd34a92b2b595ce29b85b82a/lua/completion/hover.lua#L261

But padding is added after trimming, which will fill empty lines with spaces:

https://github.com/nvim-lua/completion-nvim/blob/8aecb23b5421fa3fdd34a92b2b595ce29b85b82a/lua/completion/hover.lua#L162

**Comment by sentriz** [comment]
a quick fix for me was `highlight mkdLineBreak guifg=none guibg=none`

**Comment by haorenW1025** [comment]
@sentriz That's a possible fix, but the main issue should still be fixed. I'll look into it.

**Comment by haorenW1025** [comment]
Should be fixed by the latest commit.

**Comment by archseer** [comment]
Fixed! Interestingly, the built-in LSP has the same bug with function signature popups though.
