### ISSUE TITLE
Per buffer options

### ISSUE THREAD

**Issue by tricktux** [nvim-lua/completion-nvim#185]
There are some options that would benefit from support of being set per buffer. Like setting them from an `ftplugin` for example.

I can see clearly `g:completion_trigger_character` being one. But there may be others. I'll leave to the author discretion.

Thanks for a great plugin! ❤️

**Comment by haorenW1025** [comment]
Maybe you should take at look at [wiki](https://github.com/nvim-lua/completion-nvim/wiki/per-server-setup-by-lua), it can basically let you set option in a per-server based.

**Comment by tricktux** [comment]
Yeap! My bad. I just notice that.

I do have one unrelated question though. It's a hard question. I'll do my best too explain.

Is there conflicting or duplicate behavior If I setup completion-nvim to run on all buffers via `BufEnter` autocmd and then also setup `lsp.X.setup{.on_attach}`?
