### ISSUE TITLE
How can I remove the vim-vsnip item in completion list

### ISSUE THREAD

**Issue by glepnir** [nvim-lua/completion-nvim#188]
@haorenW1025   Hey here. I think the snippets item should not in completion list that trigger by dot.
![image](https://user-images.githubusercontent.com/41671631/91978775-4bed4500-ed57-11ea-96d8-0d60854e8a2e.png)

**Comment by hrsh7th** [comment]
It's an interesting idea.

I think it would be good to ignore sources that do not triggered by character if another source triggered by character.

**Comment by glepnir** [comment]
This is a common practice, such as deoplete and coc, I have only used them. They will not add the snippet to the completion list when starting with a point to complete.

**Comment by Xuyuanp** [comment]
```vim
    let g:completion_chain_complete_list = {
                \ 'default': {
                \   'default': [
                \      {'complete_items': ['lsp']},
                \      {'complete_items': ['snippet']},
                \   ],
                \ },
                \ }
```

**Comment by glepnir** [comment]
This option works. but If i set these. seems like  I can't get snippets in completion list? It shoud give me
 `pa vim-vsnip Package`
![image](https://user-images.githubusercontent.com/41671631/92007767-eb6eff80-ed78-11ea-983e-2a52692de212.png)

**Comment by glepnir** [comment]
Aha Thanks when I config it. seems like works fine.
