### ISSUE TITLE
 When integrating with a personal lsp client, I can't get the completion right away.

### ISSUE THREAD

**Issue by glepnir** [nvim-lua/completion-nvim#191]
Hy. I write a easy lsp client based on neovim built-in lsp.  I set completion-nvim and my personal startup lsp method to set lazyload as InsertEnter. They all work for now. But the problem is that I can't get the completion options when I enter insert mode for the first time, if I do some operations. Then I will be complemented. These code that I  integrating with completion-nvim
```lua
   local timer = vim.loop.new_timer()
  timer:start(50,0,vim.schedule_wrap(function()
    local loaded,completion = pcall(require,'completion')
    if loaded then
      server[buf_filetype].on_attach= completion.on_attach;
      local new_config = vim.tbl_extend("error",add_options(server[buf_filetype]), {
        root_dir = root_dir;
      })
      client_id = vim.lsp.start_client(new_config)
      lsp_cache_store[root_dir] = client_id
      vim.lsp.buf_attach_client(bufnr, client_id)
      timer:stop()
      timer:close()
    end
  end))
```
useful gif
![test](https://user-images.githubusercontent.com/41671631/92119638-ab685500-ee2a-11ea-9b33-7ff6d18ea92b.gif)

**Comment by haorenW1025** [comment]
Hmm so all of this code you posted are called when `InsertEnter`? The `on_attach` function sets up some `InsertEnter` autocmd and those are required completion-nvim to be working properly. Maybe this is the reason that things work fine when you enter insert mode second time.

**Comment by glepnir** [comment]
I tried to call completion. on_Insert Enter () but the result is same…

--------------原始邮件--------------
发件人："haorenW1025 "<notifications@github.com&gt;;
发送时间：2020年9月4日(星期五) 凌晨1:51
收件人："nvim-lua/completion-nvim" <completion-nvim@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [nvim-lua/completion-nvim]  When integrating with a personal lsp client, I can't get the completion right away. (#191)
-----------------------------------

 

 
Hmm so all of this code you posted are called when InsertEnter? The on_attach function sets up some InsertEnter autocmd and those are required completion-nvim to be working properly. Maybe this is the reason that things work fine when you enter insert mode second time.

**Comment by haorenW1025** [comment]
Hmm I never have the need to call `on_InsertEnter` outside of completion-nvim... Another possible thing is on_attach will set `completion-enable` buffer variables. If you're going to call `on_InsertEnter` only you might have to turn the variable on too.

**Comment by glepnir** [comment]
@haorenW1025  I saw it. Ok i wil give it try.

**Comment by glepnir** [comment]
It works. but another question. the snippet doesn't work. I used the vsnip. seems like completion-nvim redefine the confirm and I need to call it.
![test](https://user-images.githubusercontent.com/41671631/92212637-dacba000-eec4-11ea-81b6-8bb774d14e6d.gif)

**Comment by haorenW1025** [comment]
Ahh there's also some dependency here, you should call `lua require'completion'.confirmCompletion()` before completeDone. But this might be refactored out later though.

**Comment by glepnir** [comment]
I saw it just set the `manager.confirmedCompletion` to ture. then call it on `on_CompleteDone()` then exec `hasConfirmedCompletion()` .And the  `hasConfirmedCompletion()` is a local function. I can't call it.  I call the `confirmCompletion()` but nothing happend.
```lua
  local timer = vim.loop.new_timer()
  timer:start(50,0,vim.schedule_wrap(function()
    local loaded,completion = pcall(require,'completion')
    if loaded then
      -- When require completion success,We call the on_InsertEnter by ourself.
      -- Must set the completion_enable to 1
      vim.api.nvim_buf_set_var(0, 'completion_enable', 1)
      completion.confirmCompletion()
      completion.on_InsertEnter()
      -- config the server config on_attach
      server[buf_filetype].on_attach= completion.on_attach
      -- build a new server config
      local new_config = vim.tbl_extend("error",add_options(server[buf_filetype]), {
        root_dir = root_dir;
      })
      -- start a new lsp server and store the cliend_id
      client_id = vim.lsp.start_client(new_config)
      if client_id ~= nil and timer:is_closing() == false then
        lsp_cache_store[root_dir] = client_id
        vim.lsp.buf_attach_client(bufnr, client_id)
        timer:stop()
        timer:close()
      end
    end
  end))

```

**Comment by haorenW1025** [comment]
Not sure what actually is happened now... Actually I don't think `on_attach` should be lazyload when insertEnter because it set up multiple autocmd (as you might see in the source code). The proper way should be calling it on BufEnter, also the overhead of setting those autocmd up shouldn't be that heavy so there is no need to lazyload it.

**Comment by glepnir** [comment]
Thanks for your explanation, I think the plugin should only provide functions and api. So users can customize more things based on them. BufEnter will be loaded at startup. I don't want to affect my startup time because of it. For me, I prefer the plugin to enable it where it is needed.
