### ISSUE TITLE
Completions from rls (rust) are inserted with function signature

### ISSUE THREAD

**Issue by ybc37** [nvim-lua/completion-nvim#193]
In rust (with rls), after completing a function call, the whole function signature (-> with parameters) is inserted as text. So it's always needed to override those manually, what is pretty time consuming and annoying ;)

It's hard for me to tell if it's an issue in completion-nvim, neovim or rls. But as the issue occurs when selecting completion results, I hope that's the right place.

**My testing minimal init.vim**
My (lsp) config can be found [here](https://github.com/ybc37/dotfiles/blob/master/nvim/.config/nvim/init.vim#L264).
I also tested and reproduced the issue with this minimal config:
```viml
call plug#begin("~/.local/share/nvim/plugged")
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.rls.setup{on_attach=require'completion'.on_attach}
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
set completeopt=menuone,noinsert,noselect
```
Tested with latest neovim as of today (2020-09-04, 3acfefb63).
rls is installed with rustup: `rustup component add rls rust-analysis rust-src`

**How to reproduce**
1. Open a rust file and make sure rls is attached and working
2. Type `String::from` -> completions show up
3. Select the first result -> text is now `String::from(s: &String)` and cursor is at the end

**Expected behavior**
Like with other LSPs (e.g. pyls)
1. Completions show function `String::from(s: &String)`
2. Selecting the result will insert `String::from`, so it's possible to continue with the arguments
3. While typing the arguments, the help/description of them shows up

See also [this](https://asciinema.org/a/0OGvB8ECAjaV0abEOSH8BsqHY) recording in which I first show the expected behavior with pyls and then the issue with rls.

**Comment by f-person** [comment]
Same happens for Go with gopls

**Comment by Xuyuanp** [comment]
Please see #175

**Comment by f-person** [comment]
> Please see #175

Thanks! This works well.

**Comment by haorenW1025** [comment]
That's the snippets from LSP, so there's nothing I can do from completion-nvim. One solution you can use is use `vim-vsnip`(plus `vim-vsnip-integ` to have nice expansion of the snippets and it works out of the box with completion-nvim. Another solution is follow the code snippets in #178 and disable all LSP snippets.

**Comment by ybc37** [comment]
Thanks for helping and pointing to solutions!

Unfortunately, I can't make it work with `vim-vsnip` (+ `vim-vsnip-integ`). I have the feeling I'm missing something :( Installed both plugins, read the docs, played around with config, mappings, used a minimal vim config, healthcheck is fine,... Still the behavior is exactly the same as before.
Maybe someone got it work can describe the steps and maybe how to use it? Any help would be really appreciated!

Disabling the snippet capability works, though.

**Comment by haorenW1025** [comment]
@ybc37 Can you post your minimal config? I've tested it and arguments expansion works great on my side with rls and vim-vsnip(vim-vsnip-integ). It'd be better if you can post it so me and maybe @hrsh7th can help find out what went wrong.

**Comment by hrsh7th** [comment]
It seems misconfiguration for the LSP server.

https://github.com/ybc37/dotfiles/blob/master/nvim/.config/nvim/init.vim#L297

You should set `snippetSupport=true` like as below.

```
  lua require'nvim_lsp'.rls.setup{
  \   capabilities = {
  \     textDocument = {
  \       completion = {
  \         completionItem = {
  \           snippetSupport = true
  \         }
  \       }
  \     }
  \   },
  \ }
```

**Comment by hrsh7th** [comment]
Hm...
The `snippetSupport=true` seems to make confusing for some users.
The same question seems to be posted many times

**Comment by ybc37** [comment]
I thought `snippetSupport` defaults to `true`? If I set it to `false` it makes a different (function parameters are not inserted anymore).

Anyway, this is the minimal config I tested with:

```vim
call plug#begin("~/.local/share/nvim/plugged")
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
    Plug 'hrsh7th/vim-vsnip'
    Plug 'hrsh7th/vim-vsnip-integ'
call plug#end()

lua require'nvim_lsp'.rls.setup{ on_attach=require'completion'.on_attach, capabilities = {
            \    textDocument = {
            \      completion = {
            \        completionItem = {
            \          snippetSupport = true
            \        }
            \      }
            \    }
            \  },
            \}

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
let g:completion_enable_snippet = 'vim-vsnip'

" Expand
imap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'

" Expand or jump
imap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
smap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'

" Jump forward or backward
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```

My test case is trying to complete `String::from([...])` (as in the screencast above). I think the `vsnip#[...]` functions return false. Also the completions of `String::from` aren't listed as snippets, but as usual functions (when using UltiSnips, the snippets were marked as such).

Again, thanks for your help :) I can't look at it the next days, but will for sure next weekend or so.
