### ISSUE TITLE
user_data a nil value.

### ISSUE THREAD

**Issue by glepnir** [nvim-lua/completion-nvim#194]
Occasionally get such errors. What might be missing?
```
Error detected while processing CompleteDone Autocommands for "<buffer=3>":
E5108: Error executing lua ...s/github.com/nvim-lua/completion-nvim/lua/completion.lua:98: attempt to in
dex field 'user_data' (a nil value)
```

**Comment by haorenW1025** [comment]
Should be fixed in the latest commit. Please update and check.

**Comment by glepnir** [comment]
yes should be check if it's nil. aha.. I had fix it,But forget send pr.

**Comment by haorenW1025** [comment]
I normally make sure `user_data` is not nil when I'm inserting complete_items... But still checking if it's nil is not a big deal:)

**Comment by glepnir** [comment]
Another question , can we trigger signature help when we confirm  like coc?
![image](https://user-images.githubusercontent.com/41671631/92319421-83efd300-f04a-11ea-9d1d-dda64f25fa4a.png)

**Comment by haorenW1025** [comment]
Not sure what you mean be `when we confirm`... Feel free to open another PR and elaborate more on it:)
