### ISSUE TITLE
Possibly conflicting with Ultisnips?

### ISSUE THREAD

**Issue by sharksforarms** [nvim-lua/completion-nvim#204]
**My testing minimal init.vim**
```viml
call plug#begin('~/.vim/plugged')
    Plug 'neovim/nvim-lsp'
    Plug 'nvim-lua/completion-nvim'
    Plug 'SirVer/ultisnips'
    Plug 'honza/vim-snippets'
call plug#end()

lua require'nvim_lsp'.rust_analyzer.setup{on_attach=require'completion'.on_attach}
au Filetype rust setl omnifunc=v:lua.vim.lsp.omnifunc

" Note: UltiSnips defaults to <tab>
" let g:UltiSnipsExpandTrigger = "<tab>"

let g:completion_enable_snippet = 'UltiSnips'

" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
Attempt to cycle through or complete something, the tab on the completion menu seems to be overridden by Ultisnips 

![Peek 2020-09-11 19-46](https://user-images.githubusercontent.com/10912917/92981383-8b0e4b00-f467-11ea-9518-3808befc2041.gif)

**Expected behavior**
Pop-up including both snippets and completions and tab to cycle through

By changing `g:UltiSnipsExpandTrigger` from `<tab>` to something else, it seems to fix the issue.

**Comment by haorenW1025** [comment]
I can't do anything with this issue though because Ultisnips overwrite the keymaps... Please consider changing the expand keys for ultisnips or using `\<c-n>` and `\<c-p>` to navigate through popup menu.
