### ISSUE TITLE
Fix `Plug` in trouble-shooting page

### ISSUE THREAD

**Issue by sharksforarms** [nvim-lua/completion-nvim#205]
Just noticed this when creating another report:

https://github.com/nvim-lua/completion-nvim/wiki/trouble-shooting#test-completion-nvim-with-a-clean-enviornment

`Plug 'haorenW1025/completion-nvim'`

should be

`Plug 'nvim-lua/completion-nvim'`

**Comment by haorenW1025** [comment]
Fixed. Thanks for the report!

**Comment by sharksforarms** [comment]
Still one more occurrence in: https://github.com/nvim-lua/completion-nvim/wiki/trouble-shooting#check-if-the-problem-is-in-completion-nvim-or-its-lsp-specific
