### ISSUE TITLE
Completion window is too wide

### ISSUE THREAD

**Issue by Ogromny** [nvim-lua/completion-nvim#206]
Hi,

Is it possible to truncate completion suggestion like in ncm2 ?

Actual:
![Actual](https://i.imgur.com/kgSdg7n.png)

Ncm2 with truncate (three dot):
![NCM2](https://user-images.githubusercontent.com/51378896/58932549-76231200-8764-11e9-82a4-2c23ecaad4cb.png)

**Comment by haorenW1025** [comment]
I've added `g:completion_menu_length` in the PR. The default value is 0(which means no truncate at all). Can you check if it works for you?

**Comment by Ogromny** [comment]
Thanks it's works !
