### ISSUE TITLE
How to change the text that is shown on the right side of completions?

### ISSUE THREAD

**Issue by blackCauldron7** [nvim-lua/completion-nvim#214]
Like UltiSnips or builtins.

I want to change these to some icons in my font.

**Comment by skbolton** [comment]
Check the wiki https://github.com/nvim-lua/completion-nvim/wiki/Customizing-LSP-label

**Comment by blackCauldron7** [comment]
Yeah I get that I can change LSP labels

**Comment by haorenW1025** [comment]
Hmm currently you can't change the label other than lsp, but that shouldn't be hard to implement.

**Comment by haorenW1025** [comment]
Please try the latest commit

**Comment by blackCauldron7** [comment]
Any docs?

**Comment by blackCauldron7** [comment]
Documentation?
