### ISSUE TITLE
Emmet Support

### ISSUE THREAD

**Issue by blackCauldron7** [nvim-lua/completion-nvim#215]
**Is your feature request related to a problem? Please describe.**
It's painful to write html without emmet

**Describe the solution you'd like**
Emmet support for completion-nvim

**Describe alternatives you've considered**
UtliSnips with emmet plugin but UltiSnips is painstakingly slow.

**Comment by glepnir** [comment]
yep we should be has a completion source from emmet.

**Comment by haorenW1025** [comment]
I never done some serious html development so I have zero experience on using emmet...It would be better if others that have more knowledge on emmet can implement it.

**Comment by blackCauldron7** [comment]
I could try to implement it although are there any docs on how to add completion sources?

**Comment by haorenW1025** [comment]
See wiki for some guide. Also I think there are some links in README which links to other external sources and that might be helpful. Feel free ask me anything if you're stuck:)

**Comment by blackCauldron7** [comment]
@haorenW1025 The prefix resets when a character like `>, #, .` are typed but emmet can't work without those. Is there any way to include those in prefix?

**Comment by aca** [comment]
@haorenW1025 @blackCauldron7 @glepnir
I needed something to replace coc-emmet. And I just implemented it as another language server. Could you try this out?
https://github.com/aca/emmet-ls

**Comment by blackCauldron7** [comment]
> @haorenW1025 @blackCauldron7 @glepnir
> I needed something to replace coc-emmet. And I just implemented it as another language server. Could you try this out?
> https://github.com/aca/emmet-ls

It expands but doesn't function properly i have opened a more elaborate issue in your repository.
@aca

**Comment by yashguptaz** [comment]
Any updates about Emmet being implemented in completion-nvim?
How can I use Emmet with comlpetion-nvim?
