### ISSUE TITLE
Can't get the path complete item.

### ISSUE THREAD

**Issue by glepnir** [nvim-lua/completion-nvim#216]
Can't get the path completion items. my complete list
```vim
    let g:completion_chain_complete_list = [
      \  {'complete_items': ['lsp']},
      \  {'complete_items': ['snippet']},
      \  {'complete_items': ['buffers']},
      \  {'complete_items': ['path'],'triggered_only' : ['/']},
      \  {'mode': '<c-p>'},
      \  {'mode': '<c-n>'}
    \]
```
I can confirm that the `lsp snippet buffers` both work fine.

**Comment by haorenW1025** [comment]
It seems to work fine on my side. Can you try to test it using minimal config?

**Comment by glepnir** [comment]
It's wired. Because other sources are working fine. Will give it a try when have time.

**Comment by glepnir** [comment]
...remove path item to the first.. works..Don't know why.

**Comment by krisfans** [comment]
> 
> 
> ...remove path item to the first.. works..Don't know why.

It seems only the first item works...and othrt complete_items will be ignore
