### ISSUE TITLE
Weird completion behavior

### ISSUE THREAD

**Issue by quantum-booty** [nvim-lua/completion-nvim#219]
The autocompletion would sometimes fill the inside of the function.
![image](https://user-images.githubusercontent.com/28958399/94037397-39e24d80-fdbd-11ea-990e-3a7acfb5fcac.png)
This behaviour seems to happen when I wait for auto-trigger:
plt. -> wait for auto-trigger -> plt.plo -> select completion -> plt.plot(scalex=..., scaley=..., data=...)
Type very fast plt.plo -> select completion -> plt.plot()

Update:
This issue seems to be specific to jedi, I tried pyls and it doesn't have this issue.

There is also weird auto-hover behaviour that depends on whether I wait for auto-trigger. See this [thread  ](https://github.com/nvim-lua/completion-nvim/issues/218)
```


call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
call plug#end()

set updatetime=50
set completeopt+=menuone,noinsert,noselect,   " preview
set completeopt-=preview
set shortmess+=c " Don't pass messages to |ins-completion-menu|.


"------------------- Nvim-lsp settings ----------------------------
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Matching Strategy
let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
" let g:completion_sorting = "none"
let g:completion_matching_ignore_case = 1
let g:completion_enable_auto_hover = 1
let g:completion_timer_cycle = 80 "default value is 80

lua <<EOF
--require'nvim_lsp'.pyls.setup{on_attach=require'completion'.on_attach}
require'nvim_lsp'.jedi_language_server.setup{on_attach=require'completion'.on_attach}
EOF

autocmd BufEnter * lua require'completion'.on_attach()


```

**Comment by haorenW1025** [comment]
This is not an issue, those are the snippets came from LSP. You can disable it by
```
require'nvim_lsp'.vimls.setup{
  on_attach = on_attach;
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = false
        }
      }
    }
  },
}
```
Or you can use `vim-vsnip` and `vim-vsnip-integ` to expand the snippets items.
