### ISSUE TITLE
Can't disable trigger character

### ISSUE THREAD

**Issue by quantum-booty** [nvim-lua/completion-nvim#220]
After setting :completion_trigger_character = [], the completion is still triggering at dot, and the below command outputs {'.'}
`:lua print(vim.inspect(vim.lsp.buf_get_clients()[1].server_capabilities.completionProvider.triggerCharacters)) 
`

```
call plug#begin('~/.config/nvim/plugged')
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
call plug#end()
lua require'nvim_lsp'.pyls.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
let g:completion_trigger_character = []
```

**Comment by haorenW1025** [comment]
That's the expected behavior, `completion-nvim` respect the triggerCharacters of LSP, triggerCharacters only added to this list. The behavior also documented in README.
