### ISSUE TITLE
Mark hover and floating markdown buffers to avoid loading ftplugins

### ISSUE THREAD

**Issue by tricktux** [nvim-lua/completion-nvim#223]
I was hitting a performance issue, I realized that auto completion was very slow, when I set the profiler I realized that my `ftplugin/markdown.vim` was the root cause. I have quite hefty `ftplugin`, plus multiple plugins that are loaded for markdown buffers.

This is an issue because these buffers are created to display signature info, it would be great if there was a way to mark these buffers and floating windows so that it could be avoided to load `ftplugin` and other plugins on these buffers.

This is probably a problem for `nvim-lspconfig` as well.

What I am thinking is probably setting something like: `b:floating_signature` or something of the sort, that could be checked in the `after/ftplugin/markdown.vim` and not source the file if found. Ideally these could be a special  kind of window where no `after/*` plugins are loaded, I am thinking like `nerdtree/ctrlp/tagbar` that have special window names that can ignored in multiple plugins.

**Comment by haorenW1025** [comment]
Hmm I think that's because the hover and signature help callbacks set the floating filetype as markdown. A workaround is to manually trigger hover and signature by disable the auto hover and auto signature. Setting a buffer variable shouldn't be too hard though.

**Comment by haorenW1025** [comment]
I've setup a buffer variable `b:lsp_floating` to true for the floating window in hover and signature_help. Please check if it resolve your issue.

**Comment by tricktux** [comment]
Thank you. This does fix the performance problems. However does require user action. I'll experiment with seeing these buffers to a different filetype and then applying the markdown highlight.
