### ISSUE TITLE
[Trigger character completion] Ruby `@` is not auto-completing even though it is a trigger character

### ISSUE THREAD

**Issue by bluz71** [nvim-lua/completion-nvim#230]
Hello completion-nvim team,

I am a current [LSC](https://github.com/natebosch/vim-lsc) user that is looking at Neovim LSP + completion.nvim. LSC is a Vim/Neovim LSP client written in Vimscript.

On issue I notice is that `@` character in Ruby is not auto-completing in completion-nvim whilst in LSC it does.

Initially I created Neovim issue [12997](https://github.com/neovim/neovim/issues/12997) but I ended up closing it and have opened up this one instead.

Initially I thought Neovim LSP was not negotiating `triggerCharacters` from the language server, but turns it does according to:

```viml
:lua print(vim.inspect(vim.lsp.buf_get_clients()[1].server_capabilities.completionProvider.triggerCharacters))
```

I get `{ ".", ":", "@" }` which is the same set of characters that LSC negotiates. Notice the `@` character.

Minimal `init.vim` that exhibits the issue:

```viml
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
call plug#end()

lua <<EOF
local nvim_lsp = require'nvim_lsp'
local completion = require'completion'

local lsp_on_attach = function(client)
  completion.on_attach(client)
  print("LSP started.")
end

nvim_lsp.solargraph.setup {
  on_attach = lsp_on_attach,
}
EOF
```

The Ruby Solargraph language server needs to be installed.

Minimal Ruby file that exhibits the issue (needs to be inside a Git repository directory):

```ruby
class FooBar
  def initialize
    @hello = "hello"
  end

  def baz
    @<<CURSOR-HERE>>
  end
end

foo = Foobar.new
```

Notice the `<<CURSOR-HERE>>` position.

With LSC client I get this auto-completion result:

![LSC_Ruby](https://user-images.githubusercontent.com/11382509/94772999-4179a600-03fe-11eb-86a2-a43c6d776aa8.png)

With Neovim LSP + completion-nvim I get no auto-completion:

![completion-nvim](https://user-images.githubusercontent.com/11382509/94773025-4e969500-03fe-11eb-9218-e8763d4e00d0.png)

Maybe a configuration issue? Maybe not.

It would be appreciated if we can resolve this since it does seem a regression compared with current Vimscript LSP clients such as LSC.

Best regards.

**Comment by vigoux** [comment]
Hey, did you have any chance to look at [this](https://github.com/nvim-lua/completion-nvim#trigger-characters) ?
I know that what you want is having this autoatically, but maybe there is a way to sync the server `triggerCharacters` and those mentionned above.

**Comment by bluz71** [comment]
@vigoux,

I have experimented with that option. It makes no difference. `@` is not completing in completion-nvim even if I hard code it in `g:completion_trigger_character`.

Note, I now believe that the server `triggerCharacters` are correctly being negotiated by Neovim LSP as noted by:

```viml
:lua print(vim.inspect(vim.lsp.buf_get_clients()[1].server_capabilities.completionProvider.triggerCharacters))
```

For Ruby it lists: `{ ".", ":", "@" }`.

So I think the trigger characters are being collected correctly. But something is not working correctly in terms of automatically completing after a trigger character has been typed in insert mode.

The comparison is against [LSC](https://github.com/natebosch/vim-lsc) which does automatically complete after the `@` trigger. For those interested, [this is my LSC configuration](https://github.com/bluz71/dotfiles/blob/master/vim/plugin/lsc.vim) and this is my [Neovim LSP + completion-nvim configuration](https://github.com/bluz71/dotfiles/blob/master/vim/lua/lsp-config.lua).

Best regards.

**Comment by haorenW1025** [comment]
This doesn't look right... I'll look into this.

**Comment by bluz71** [comment]
Thanks @haorenW1025.

If there are any tests or experiments you need me to run, I will be more than happy to assist.

**Comment by haorenW1025** [comment]
I'm having trouble setting up solargraph... It doesn't seems to load up even if I'm in a git repository... Do I have to add some extra configuration to get that working? Sorry I've never worked in Ruby before..

**Comment by bluz71** [comment]
It may be better to check out a proper Ruby on Rails repository.

Checkout my toy Rails application: https://github.com/bluz71/platters

Then create the test Ruby file from above inside the base of that checked out Rails application. Your Solargraph may be looking for a `Gemfile`.

If that still doesn't work then run `bundle install` at the base directory of `platters`. I suspect this step isn't needed.

We want to get a reproducable test case for you.
We even need to get LSC working for you (maybe, maybe not).

**Comment by bluz71** [comment]
Also run these commands inside the `platters` directory:

- `solargraph download-core`

- `solargraph bundle`

**Comment by bluz71** [comment]
Note, I install Solargraph via `gem install solargraph` (not via nvim-lspconfig).

**Comment by haorenW1025** [comment]
Thanks for the guide. I can reproduce the issue now:)

**Comment by haorenW1025** [comment]
The first thing I've noticed is the completion doesn't work even if you use the omnifunc complete of built-in lsp. So this issue should only be fixed in the core repository. I'm guessing that the matching function below doesn't match the `@` character therefore the completion doesn't work.
```lua
local textMatch = vim.fn.match(line_to_cursor, '\\k*$')
```

**Comment by bluz71** [comment]
@haorenW1025,

Thanks for looking into this.

Ok, we need to alert Neovim upstream of this issue.

Probably best that I reopen [Neovim 12997](https://github.com/neovim/neovim/issues/12997). Your participation over there in that issue will be appreciated.

We really want to fix this issue since it really does impact users, basically completions from certain trigger characters is not working. It is a Neovim LSP bug.

**Comment by bluz71** [comment]
Neovim [12997](https://github.com/neovim/neovim/issues/12997) has been re-opened.

It is like a game of tennis, first Neovim, then completion.nvim, back to Neovim.

Should we close this issue? I suspect yes.

**Comment by bluz71** [comment]
This is an upstream Neovim LSP <—> Solargraph issue.

Closing this issue.
