### ISSUE TITLE
What is used for highlighting

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [nvim-lua/completion-nvim#243]
Highlighting doesn't look great with my colorscheme . . .

![image](https://user-images.githubusercontent.com/48275422/96012406-f9b24000-0e3b-11eb-902e-1d2652ba70b0.png)

What highlights can I set to change this? I was unable to find anything in the wiki, issues, or searching through the codebase(using github's search).

**Comment by lithammer** [comment]
I think that's just the regular markdown syntax highlighting of your colorscheme.

**Comment by Th3Whit3Wolf** [comment]
Is there a way to change it to something else?

**Comment by lithammer** [comment]
Well it's using markdown because that's what rust-analyzer is giving you. However I think you there's an alternative to use plaintext instead using something like this:

```lua
nvim_lsp.rust_analyzer.setup({
   capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          documentationFormat = vim.lsp.protocol.MarkupKind.PlainText
        }
      }
    }
  }
})
```

**Comment by haorenW1025** [comment]
As @lithammer mention above, the highlight is markdown syntax. You should try debugging it by opening a markdown files and use `:hi markdown` and then tab to get all possible markdown syntax highlight. Try tweaking them until it looks better.

**Comment by Th3Whit3Wolf** [comment]
> Well it's using markdown because that's what rust-analyzer is giving you. However I think you there's an alternative to use plaintext instead using something like this:
> 
> ```lua
> nvim_lsp.rust_analyzer.setup({
>    capabilities = {
>     textDocument = {
>       completion = {
>         completionItem = {
>           documentationFormat = vim.lsp.protocol.MarkupKind.PlainText
>         }
>       }
>     }
>   }
> })
> ```

I get an error

```
Error executing luv callback
/usr/share/nvim/runtime/lua/vim/lsp/log.lua:62 attempt to call field 'getinfo' (a nil value)
```

Is it possible to make that output it's own filetype so that I can create my own syntax file?

**Comment by theHamsta** [comment]
There's a highlight group for floating windows `NormalFloat`. Its background and basic foreground usually inherits your popup menu.

**Comment by Th3Whit3Wolf** [comment]
> There's a highlight group for floating windows `NormalFloat`. Its background and basic foreground usually inherits your popup menu.

Is that the only other option? I'd really prefer to keep NormalFloat the same as Pmenu.

**Comment by theHamsta** [comment]
I believe Normal of some identifiers makes them stand out. I have similar backgrounds in my floating windows.

**Comment by Th3Whit3Wolf** [comment]
![image](https://user-images.githubusercontent.com/48275422/96114973-35054b00-0ede-11eb-9a32-7693d2faa9fd.png)

I got this close by putting this in `after/ftplugin/rust`

```vim
function s:rustdoclsphilight()
	if &background ==# 'dark'
		let l:color = '#5d4d7a'
	else
		let l:color = '#e2e0ea'
	endif
	exec 'hi markdownItalic guibg='.l:color
	exec 'hi markdownAutomaticLink guibg='.l:color
	exec 'hi markdownBlockquote guibg='.l:color
	exec 'hi markdownBold guibg='.l:color
	exec 'hi markdownBoldDelimiter guibg='.l:color
	exec 'hi markdownBoldItalic guibg='.l:color
	exec 'hi markdownBoldItalicDelimiter guibg='.l:color
	exec 'hi markdownCode guibg='.l:color
	exec 'hi markdownCodeBlock guibg='.l:color
	exec 'hi markdownCodeDelimiter guibg='.l:color
	exec 'hi markdownError guibg='.l:color
	exec 'hi markdownEscape guibg='.l:color
	exec 'hi markdownFootnote guibg='.l:color
	exec 'hi markdownFootnoteDefinition guibg='.l:color
	exec 'hi markdownH1 guibg='.l:color
	exec 'hi markdownH2 guibg='.l:color
	exec 'hi markdownH3 guibg='.l:color
	exec 'hi markdownH4 guibg='.l:color
	exec 'hi markdownH5 guibg='.l:color
	exec 'hi markdownH6 guibg='.l:color
	exec 'hi markdownHeadingDelimiter guibg='.l:color
	exec 'hi markdownHeadingRule guibg='.l:color
	exec 'hi markdownId guibg='.l:color
	exec 'hi markdownIdDeclaration guibg='.l:color
	exec 'hi markdownIdDelimiter guibg='.l:color
	exec 'hi markdownItalic guibg='.l:color
	exec 'hi markdownItalicDelimiter guibg='.l:color
	exec 'hi markdownLineBreak guibg='.l:color
	exec 'hi markdownLineStart guibg='.l:color
	exec 'hi markdownLink guibg='.l:color
	exec 'hi markdownLinkDelimiter guibg='.l:color
	exec 'hi markdownLinkText guibg='.l:color
	exec 'hi markdownLinkTextDelimiter guibg='.l:color
	exec 'hi markdownListMarker guibg='.l:color
	exec 'hi markdownOrderedListMarker guibg='.l:color
	exec 'hi markdownRule guibg='.l:color
	exec 'hi markdownUrl guibg='.l:color
	exec 'hi markdownUrlDelimiter guibg='.l:color
	exec 'hi markdownUrlTitle guibg='.l:color
	exec 'hi markdownUrlTitleDelimiter guibg='.l:color
	exec 'hi markdownUrlValid guibg='.l:color
endfunction!

call <SID>rustdoclsphilight()
```

It's in a function so I can call it on colorschemechange

I might be able to get the rest by making putting a syn keyword block `before/ftplugin/markdown.vim` and setting highlights in `after/ftplugin/rust.vim`. I'm not sure though.
