### ISSUE TITLE
Add option to truncate item.menu(description) 

### ISSUE THREAD

**Issue by sjeon7** [nvim-lua/completion-nvim#245]
<img width="1977" alt="스크린샷 2020-10-19 오후 12 04 29" src="https://user-images.githubusercontent.com/26849596/96397217-fc2de480-1203-11eb-95bd-e25e592e149e.png">

**Is your feature request related to a problem? Please describe.**
There is an option for truncating the item name using g:completion_menu_length (yellow box in the picture above).
However, item.menu(description) is sometimes too long which blocks the hover. The section is red box in the picture above.
It would be great if there is an option for truncating item.menu(description) section.

**Describe the solution you'd like**
I personally modified section in `completion-nvim/lua/completion/util.lua` like the code below.
```
function M.addCompletionItems(item_table, item)
  -- word cannot be nil
  if item.word == nil then return end
  local menu_length = opt.get_option('menu_length')
  if menu_length ~= 0 then
    if string.len(item.abbr) > menu_length then
      item.abbr = string.sub(item.abbr, 0, menu_length).."..."
    end
  end
  table.insert(item_table, {
      word = item.word,
      abbr = item.abbr or '',
      kind = item.kind or '',
      -- modified section start
      menu = string.sub(item.menu,0,20) or '', 
      -- modified section end
      info = item.info or '',
      priority = item.priority or 1,
      icase = 1,
      dup = item.dup or 1,
      empty = 1,
      user_data = item.user_data or {},
    })
end
```

<img width="2021" alt="스크린샷 2020-10-19 오후 12 21 28" src="https://user-images.githubusercontent.com/26849596/96397954-9fcbc480-1205-11eb-8621-b36802f959bd.png">
Which this code will truncate item.menu to 20 characters like the picture above. Just like g:completion_menu_length option, option to truncate item.menu can be implemented.

Thank you for the awesome plugin!

**Comment by sjeon7** [comment]
> <img alt="스크린샷 2020-10-19 오후 12 04 29" width="1977" src="https://user-images.githubusercontent.com/26849596/96397217-fc2de480-1203-11eb-95bd-e25e592e149e.png">
> 
> **Is your feature request related to a problem? Please describe.**
> There is an option for truncating the item name using g:completion_menu_length (yellow box in the picture above).
> However, item.menu(description) is sometimes too long which blocks the hover. The section is red box in the picture above.
> It would be great if there is an option for truncating item.menu(description) section.
> 
> **Describe the solution you'd like**
> I personally modified section in `completion-nvim/lua/completion/util.lua` like the code below.
> 
> ```
> function M.addCompletionItems(item_table, item)
>   -- word cannot be nil
>   if item.word == nil then return end
>   local menu_length = opt.get_option('menu_length')
>   if menu_length ~= 0 then
>     if string.len(item.abbr) > menu_length then
>       item.abbr = string.sub(item.abbr, 0, menu_length).."..."
>     end
>   end
>   table.insert(item_table, {
>       word = item.word,
>       abbr = item.abbr or '',
>       kind = item.kind or '',
>       -- modified section start
>       menu = string.sub(item.menu,0,20) or '', 
>       -- modified section end
>       info = item.info or '',
>       priority = item.priority or 1,
>       icase = 1,
>       dup = item.dup or 1,
>       empty = 1,
>       user_data = item.user_data or {},
>     })
> end
> ```
> 
> <img alt="스크린샷 2020-10-19 오후 12 21 28" width="2000" src="https://user-images.githubusercontent.com/26849596/96397954-9fcbc480-1205-11eb-8621-b36802f959bd.png">
> 
> Which this code will truncate item.menu to 20 characters like the picture above. Just like g:completion_menu_length option, option to truncate item.menu can be implemented.
> Thank you for the awesome plugin!

**Comment by sjeon7** [comment]
Similar to #206 which abbreviate item.abbr, this is request for the option to make item.menu shorter.

**Comment by haorenW1025** [comment]
That's a great suggestion. Actually the variable you mention is quite misleading. I modified the naming so that `g:completion_menu_length` will be the `item.menu`'s length and `g:completion_abbr_length` will be the `item.abbr`'s length. Please see if this PR works for you.

**Comment by sjeon7** [comment]
@haorenW1025 I checked new PR and it is working great except this part.
```
      item.abbr = string.sub(item.menu, 0, menu_length).."..."
```
Wouldn't this part be `item.menu = string.sub(item.menu, 0, menu_length).."..."`??

I also added comment on new PR. Thank you!

**Comment by haorenW1025** [comment]
That's a typo there. Should be fixed now, thanks for the report:)

**Comment by sjeon7** [comment]
@haorenW1025 Everything works well! Thank you!
I hope that new PR is merged soon.
Closing this is in favor of #250 then.
