### ISSUE TITLE
Highlight current argument in signature help

### ISSUE THREAD

**Issue by khaveesh** [nvim-lua/completion-nvim#246]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the signature help doesn't show which argument that I'm typing and it is difficult to count the number of commas to figure it out.

**Describe the solution you'd like**
In the signature help that pops up, as I type in the arguments, it should highlight the argument I'm currently typing. My intuition is that this should be based on the number of commas already typed. But some corner cases can occur such as the arguments themselves having commas. Eg - Passing a list as an argument in Python. 

**Describe alternatives you've considered**
I previously used Deoplete with echodoc which provides this feature. Also VSCode too provides this feature. I think that this would be a great addition to this already super awesome plugin.
This is an example of the feature in VSCode:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4398066/96417943-ac551a80-120f-11eb-82d3-f016cb0d5d8a.png">

**Comment by haorenW1025** [comment]
Hmm the thing is completion-nvim doesn't actually handles signature_help. It just triggers it when it's available. So although I have to admit that it seems to be a nice enhancement, it's kind of out of the scope of this plugin. I'll try look into it when I have time but probably this won't be built into this plugins.
