### ISSUE TITLE
Change auto paren behaviour

### ISSUE THREAD

**Issue by khaveesh** [nvim-lua/completion-nvim#247]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to confirm an autocompletion item, in order to have the parens inserted. I can understand this behaviour for snippets where if you complete it without confirmation, it would be disastrous.

**Describe the solution you'd like**
`<c-n>` & `<c-p>` should insert the parens automatically without needing to press the confirmation key. But this behaviour is only applicable for LSP completion items. 

**Describe alternatives you've considered**
VSCode has this behaviour:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4398066/96420176-c6442c80-1212-11eb-81b0-759fe760d3a6.gif)

**Comment by vaijab** [comment]
The vscode example you showed is a great example how it should work. Currently what I am finding quite annoying is that it does insert parenthesis but the cursor is moved to the end of a closing paren So I then have to switch to normal mode, move the cursor back and enter insert mode agian.

**Comment by Shougo** [comment]
Unfortunately, it cannot be implemented.  It is Vim/neovim completion's feature.

> VSCode has this behaviour:

You have confirmed the candidate.  So it is not `without needing to press the confirmation key`.
