### ISSUE TITLE
Autocompletion does not work with variables in PHP (Intelephense)

### ISSUE THREAD

**Issue by nkoporec** [nvim-lua/completion-nvim#252]
I just started using Nvim LSP and the completion plugin and I have an issue with autocompletion in PHP. I'm using latest Intelephense server and nightly Nvim. For some reason autocompletion does not work with variables, the popup does not filter correctly and only shows the variables if the key length is 1, anything else won't work, not even exact match. When you want to autocomplete the variable it only prints $.The strange issue is that it works normally with methods, for example after manually typing $this-> the completion from this point on will work as expected.

This is only happening with Intelephense, when I tried out with gopls it works normally, so I suspected it's either Intelephense server or maybe $ sign.

Here is a video describing my issue:

https://monosnap.com/file/TbPDYwb6oSfwEqaPPGblsXZBsRLNmz

Here are my configs:
```
	let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
	let g:completion_trigger_character = []
	lua require'nvim_lsp'.intelephense.setup{on_attach=require'completion'.on_attach}
	lua require'nvim_lsp'.tsserver.setup{ on_attach=require'completion'.on_attach }
	lua require'nvim_lsp'.gopls.setup{ on_attach=require'completion'.on_attach }

```

Any help is much appreciated!

**Comment by haorenW1025** [comment]
completion-nvim uses `iskeyword` to get the keyword for completion. I'm guessing that `$` is not a keyword by default. Try setting `:set iskeyword=@,48-57,_,192-255,$` and see if it works. Also `:h iskeyword` might also help.

**Comment by nkoporec** [comment]
Thanks for the help, unfortunately it did not work, it fixes the issue with duplicate $$ signs but it still does not autocomplete or show variables in the popup menu.

**Comment by nkoporec** [comment]
Just installed tsserver and test out variables with $ signs ($test) and it works as expected, so I believe there is something wrong with Intelephense or it's config ...

**Comment by adalessa** [comment]
Hey I have the same issue. Looking into the code I found a workaround I installed `snippets.nvim` using plug `Plug 'norcalli/snippets.nvim'
`  and set `let g:completion_enable_snippet = 'snippets.nvim'
` whit this I have it working.
To give context on why I did that was because here https://github.com/nvim-lua/completion-nvim/blob/3b6774ed1c1b4720efe3385f06883483f5e16884/lua/completion/source/lsp.lua#L34-L39 checks if snippets nvim is being used and avoid calling `vim.lsp.util.parse_snippet(item.insertText)` which was returning empty for me. 

Hope this help and have a good one.

**Comment by nkoporec** [comment]
Yep, the workaround with `let g:completion_enable_snippet = 'snippets.nvim'` works, thanks!

**Comment by danielpieper** [comment]
Worked for me in combination with `:set iskeyword=@,48-57,_,192-255,$`

**Comment by jyscao** [comment]
Just want to let the maintainers know that #333 doesn't appear to have fixed this issue. 

I still needed to apply the workaround of setting `let g:completion_enable_snippet = 'snippets.nvim'` and `set iskeyword+=$` for completion on the `$`-char to work using Intelephense.
