### ISSUE TITLE
Question: How to attach completion engine to all filetypes except one?

### ISSUE THREAD

**Issue by JanValiska** [nvim-lua/completion-nvim#265]
Currently i'm using:

`autocmd BufEnter * lua require'completion'.on_attach()`

But i wish disable it for certain types of buffers(exactly for one: clap_input).
Is there some way to attach to all buffers except buffers with certain type?

Thank you.

**Comment by theHamsta** [comment]
Does this work?
`autocmd BufEnter * lua function() if vim.bo.filetype ~= "fooo" then require'completion'.on_attach() end end`

**Comment by JanValiska** [comment]
Thank you for hint.

I finally created `myfnuctions.lua`:
```
local myfunctions =  {}

function myfunctions.on_attach()
    if vim.bo.filetype ~= "clap_input"
    then
        require'completion'.on_attach()
    end
end

return myfunctions
```

and called it from `vimrc` like:
```
autocmd BufEnter * lua require'myfunctions'.on_attach()
```

Works like a charm!
