### ISSUE TITLE
Empty field handler referenced in signature_help.lua

### ISSUE THREAD

**Issue by Iron-E** [nvim-lua/completion-nvim#270]
> ```
> Error executing vim.schedule lua callback: ...lugged/completion-nvim/lua/completion/signature_help.lua:33: attempt to index field 'handler' (a nil value) 
> ```
>
> ___
>
> _Originally posted by @yashLadha in https://github.com/nvim-lua/completion-nvim/issues/268#issuecomment-728083208_

This happens when typing in a buffer with attached LSP after #268. Screenshot:

![Error](https://user-images.githubusercontent.com/36409591/99274493-66807780-27f8-11eb-972f-777b6272c32b.png)

* Note this screenshot shows a reference to `handler` in a different file, 'hover.lua'.

Closed by #266.

**Comment by yashLadha** [comment]
Fix is already pushed into master. Can you please check with the current master?

**Comment by Iron-E** [comment]
I used master for the screenshot

**Comment by yashLadha** [comment]
It is not happening for me, can you please try updating the plugin.

**Comment by Iron-E** [comment]
After another rebase to master it doesn't happen. Closing.
