### ISSUE TITLE
Pointer sign for c functions in info popup window missing

### ISSUE THREAD

**Issue by vitautart** [nvim-lua/completion-nvim#272]
**My testing minimal init.vim**
https://gist.github.com/vitautart/76c2e13597b804ca400506906f83081c

**How to reproduce**
* Nvim nightly 0.5
* Use my init.vim
* Install all plugins
* Install clangd
* Get minimal project for c. 
* Try to call some function with arguments as pointers i.e. strcpy
* After you type name function, type "(" that triggers popup window 

**Expected behavior**
In my setup popups for function (not selection menu, but popup that appears after you type ''(" after function name) is missing pointer signs "*" for functions in c.

P.S.:Not sure if this is an issue of this plugin, or nvim lsp itself or clangd or its my setup.

**Comment by haorenW1025** [comment]
I think you mean the signature help menu. completion-nvim only calls the api automatically to open the menu for you, so it shouldn't be related here. I'm guessing the issue might comes from clangd, try ccls and see if it works better for you.
