### ISSUE TITLE
Question: How do source in the same group affect each other?

### ISSUE THREAD

**Issue by weilbith** [nvim-lua/completion-nvim#275]
Hey,

I have a question which I can't find an answer for in the docs or already open issues. So basically the header already states it, but maybe that's a bit generic. So in more detail I'm interested to know how the different speed of sources that are in the same group or side-by-side group affect the auto-completion. So for example I have `snippet` and `lsp` in my default first level group and recently also `path`. Does the auto-completion wait until all sources have responded before it publishes the completion candidates or does it immediately push when the first source responds and then continuously updates the list when the slower sources respond as well? So is the grouping only about not cluttering the completion list too much and keep it more focused or does it also relate to performance.
And a bit more special. Assuming that auto changing the source is enabled and my first group is super slow, would it then jump to the second group if that can provide candidates faster or..?

Sorry for these stupid (?) questions. Reading through them myself is a bit awkward. I'm faced with a large and complex code-base that causes heavy load on the language server. So the `lsp` source as my primary go-to is quite slow and I barely good help of auto-completion there. Although I was first not so happy about the intersection of LSP and Treesitter, I now consider to integrate Treesitter as well as a faster completion source on a first stage until LSP responds (or if Treesitter basically can't find something [correct]). Thereby I was about to edit my completion list configuration again, but had all of these questions.

**Comment by haorenW1025** [comment]
Currently, popup menu will show only after all sources in the same group have responded, and auto-changing only happens if all the sources respond but no there is no available items. This is probably not the best way related to performance though. If you have any feedback on this, please let me know:)

**Comment by weilbith** [comment]
Hmm. It would be cool if a group could populate to the same menu (means I don't switch manually to the next group/menu) but are independently pushing asynchronously to the current completion list items.
How could that be useful: you could for example combine treesitter and LSP into the first group. For complex code-bases the LSP might be slow (I saw the quite long open issue with many discussions about that). But Treesitter should remain quite fast as it is only focused on the current file. So while LSP is still working in background, the completion items of Treesitter might be already enough to help. I they don't because I want to access for example a property of something I have imported, I need to wait for LSP. But for everything buffer "internal" it would be faster.
But if the group waits until Treesitter **and** LSP are ready, the Treesitter source is likely useless since LSP should be always smarter (I would hope so). And splitting them into two groups is also not so nice, because then Treesitter would often shadow LSP if I don't switch manually. But eventually I should give it a try, because hopefully the list of Treesitter is empty if I use something external what only LSP can tell me. And then I have auto-switch that works well, as the empty response of Treesitter probably arrives earlier than LSP its. But wait, could it be that the second group get only "asked" for candidates when the first is empty. So I would get an even worse time of response when Treesitter does not find something?
