### ISSUE TITLE
[documentation] Reflect the fact that diagnostics-nvim is now deprecated

### ISSUE THREAD

**Issue by LambdaP** [nvim-lua/completion-nvim#276]
**How to reproduce**
> Detailed step to reproduce this issue.

README.md still mentions using https://github.com/nvim-lua/diagnostic-nvim, even though that project is now announced as deprecated.

**Expected behavior**
> A clear and concise description of what you expected to happen.

At least remove [the section # Compatibility with diagnostic-nvim](https://github.com/nvim-lua/completion-nvim/blob/8d137023ec64d1b3e7213087bdb2b1394a9591b2/README.md#compatibility-with-diagnostic-nvim,) but better would be to replace it with equally useful information.

**Comment by haorenW1025** [comment]
Closed by #277
