### ISSUE TITLE
How to bind confirm completion correctly

### ISSUE THREAD

**Issue by weilbith** [nvim-lua/completion-nvim#281]
Hey :wave: 

So [this](https://github.com/nvim-lua/completion-nvim/pull/7) got removed a while ago.
I'm using the _delimitMate_ plugin for completing parenthesis etc with some smart features. The issue: this maps the return key as well. So this is my current approach how to do it based on the docs for this and the other plugin:

```vim
inoremap <expr> <CR>  pumvisible() ? complete_info()["selected"] != "-1" ?
      \ "\<Plug>(completion_confirm_completion)" :
      \ "\<C-e>\<Plug>delimitMateCR" :
      \ "\<Plug>delimitMateCR"
```

So I type `myFunction`. While doing that the completion menu opens automatically. But I'm already mostly done typing and the flow is so fast, so I don't use completion. Then I type `(<CR>` at the end to pass the paramters in the new lines. The expected result with _delimitMate_ should be:

```
myFunction(
  <cursor>
)
```

Actual result (note the missing opening parenthesis as well):
```
myFunction<Plug>delimitMateCR)
```

PS: I have toggled the `completion_enable_auto_paren` but it doesn't change anything.

**Comment by weilbith** [comment]
I'm stupid. Ofc does `<expr>` not work for non-recursive mapping commands.
But I'm still missing the parenthesis. An idea?

**Comment by Julpikar** [comment]
My setting work on golang code using this configuration.
``` lua
-- my indentation on lua
vim.o.autoindent = true
vim.o.smarttab = true
vim.o.cindent = true
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.cmd('filetype indent off')

vim.g.delimitMate_expand_cr = 1
--vim.cmd('let delimitMate_expand_cr=1')
vim.g.delimitMate_jump_expansion = 1
```
On LSP completion
``` lua
vim.g.completion_confirm_key = ""
vim.cmd([[imap <expr> <cr>  pumvisible() ? complete_info()["selected"] != "-1" ? "<Plug>(completion_confirm_completion)"  : "\<c-e>\<CR>" : "\<Plug>delimitMateCR"]])
```

**Comment by weilbith** [comment]
As I switched over to `compe`, I gonna close this issue.
