### ISSUE TITLE
Auto select first completion item

### ISSUE THREAD

**Issue by haze** [nvim-lua/completion-nvim#287]
I'm trying to migrate my `coc` completion to `completion-nvim`, and one feature I'm missing is auto selecting the first completion item. I feel like this is possible, but couldn't find anything from my shallow searching. I figure opening an issue would make it easier for others to find in the future as well.

**Comment by Shougo** [comment]
```vim
set completeopt+=noinsert
```

**Comment by haze** [comment]
Thank you.

**Comment by onsails** [comment]
is it possible to autoselect only some complete_items?
My `complete_items` is `['lsp', 'snippet', 'tabnine', 'buffers']`. Can I configure the plugin to autoselect only `lsp` and `snippet` items but not `tabnine` or `buffers`?
