### ISSUE TITLE
Overlapping windows

### ISSUE THREAD

**Issue by MurdeRMelodY** [nvim-lua/completion-nvim#305]
Completion window overlaps with documentation's. Any tips on how I can fix this?

**Comment by cideM** [comment]
At least in my case the problem is that the package path is very long and it's not wrapped, as such the hover window can't shrink enough. So if there's something like `https://pkgs.go.dev/very/long/path/that/just/keeps/going/and/going` it can't shrink the hover window so it overlaps with the pum

**Comment by haorenW1025** [comment]
Can you provide proper examples for me to reproduce? This would help a lot if I want to resolve this issue.

**Comment by cideM** [comment]
Is there a Lua command I can just call to trigger a completion plus the little documentation window?
