### ISSUE TITLE
Plugin settings in lua

### ISSUE THREAD

**Issue by boydkelly** [nvim-lua/completion-nvim#307]
Is it possible at this time for the plugin settings to be entirely in lua?

I have tried a few of the settings below.   What is not comment out seems to work.   Its mostly the keybindings that either don't work (yet) or I just can't figure out the syntax.  For example the mapping of <c-p> to <Plug>(completion_trigger) will litteraly wriite <Plug>(completion_trigger) in the file.

### This seems ok:
    vim.g.completion_enable_auto_popup = 0
    vim.g.completion_enable_snippet = 'UltiSnips'

### This doesn't
    --vim.api.nvim_buf_set_keymap(0, 'i', '<c-p>', '\\<Plug>(completion_trigger)', opts)
    --vim.cmd('inoremap <c-p> <Plug>(complettion_trigger)')

    --vim.api.nvim_buf_set_keymap(0, 'i', 'j pumvisible() ?', "\\<C-N>", { expr = true, noremap = true, silent = true } ) 
    --vim.api.nvim_buf_set_keymap(0, 'i', 'k pumvisible() ?', "<C-P>", { expr = true, noremap = true, silent = true } ) 

    --vim.cmd('inoremap <expr> j pumvisible() ? "\<C-N>"')
    --vim.cmd('inoremap <expr> k pumvisible() ? "\<C-P>"')

**Comment by mjlbach** [comment]
You're missing some escaled characters, here's an example from my config (all lua)

```lua
-- Use <Tab> and <S-Tab> to navigate through popup menu
vim.api.nvim_set_keymap('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {expr = true})
vim.api.nvim_set_keymap('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<Tab>"', {expr = true})

-- Set completeopt to have a better completion experience
vim.o.completeopt="menuone,noinsert,noselect"

-- Avoid showing message extra message when using completion
vim.o.shortmess = vim.o.shortmess .. "c"

-- Chain completion list
vim.g.completion_chain_complete_list = {
            default = {
              default = {
                  { complete_items = { 'lsp', 'snippet' }},
                  { mode = '<c-p>'},
                  { mode = '<c-n>'}},
              comment = {},
              string = { { complete_items = { 'path' }} }}}
```

**Comment by boydkelly** [comment]
Thank you!   Much appreciated.
