### ISSUE TITLE
Import not done if completion is done between parenthesis with snippetSupport

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-lua/completion-nvim#308]
**My testing minimal init.vim**

So far, reproduced with jdtls and gopls.

*init.vim*
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/completion-nvim

autocmd BufEnter * lua require'completion'.on_attach()

lua << EOF
vim.o.completeopt = "menuone,noinsert,noselect"

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require'lspconfig'.gopls.setup{
	cmd = {"gopls", "serve"},
	capabilities = capabilities,
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
			staticcheck = true,
		},
	},
}

EOF
```

**How to reproduce**
Complete something between parenthesis that requires an import.  
Here's an example using gopls:

*main.go*
```go
package main

func main() {

	() // Complete here

}
```

1. Place cursor between `()` and type `fmt.`
1. Completion menu appears, select the first entry 

**Expected behavior**
Import is done as follows:

```go
package main

import(
    "fmt"
)

func main() {

	(fmt.Println) // Complete here

}
```

**Comment by haorenW1025** [comment]
Try setting
```
let g:completion_expand_characters = [' ', '\t', '>', ';', ')']
```
This issue is quite weird though because expand_characters are resolved for using snippets expansion, but here I think setting `capabilities.textDocument.completion.completionItem.snippetSupport = true` changes the behavior of `applyAdditionalTextEdits` to snippets...Setting that to false can also fix the issue on my side.

**Comment by ChrisAmelia** [comment]
Thanks, it solved the issue.
