### ISSUE TITLE
vimtex omnifunc as completion source does not open autocomplete menu

### ISSUE THREAD

**Issue by dfangx** [nvim-lua/completion-nvim#310]
**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue
File `test.vim`
```
lua require'vimtex'
let g:completion_chain_complete_list = {
           \ 'default' : [
           \     {'complete_items': ['vimtex', 'snippet']}, 
           \   ],
           \ }
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect

lua require'completion'.addCompletionSource('vimtex', require'vimtex'.complete_item)
au BufEnter * lua require'completion'.on_attach()
```

Associated `vimtex.lua` code taken from the wiki
```
local M = {}

function M.getCompletionItems(prefix)
    -- define your total completion items
    local items = vim.api.nvim_call_function('vimtex#complete#omnifunc',{0, prefix})
    return items
    
end

M.complete_item = {
    item = M.getCompletionItems
}

return M
```
**How to reproduce**
Open a *.tex file using `nvim -u test.vim`
Begin typing '\beg' or some other latex command
Autocompletion menu does not pop up

**Expected behavior**
Autocompletion menu should pop up with completion items in it.

**Comment by haorenW1025** [comment]
I think you didn't activate completion-nvim on tex buffer, normally the completion is trigger by the `on_attach` function ins LSP, but since you're not using LSP, you can do it by
```
autocmd BufEnter *.tex lua require'completion'.on_attach()
```

**Comment by dfangx** [comment]
I have this line in the minimal config:
```
au BufEnter * lua require'completion'.on_attach()
```
Doesn't call on_attach?

**Comment by haorenW1025** [comment]
Yeah it does. I somehow miss that..I've found out that you have to triggered the omni func completion first by `<c-x><c-o>` first and then the auto complete should work fine. I think it's an issue with vimtex's omni-complete though but I'm not sure.

**Comment by dfangx** [comment]
I was going through `:h complete-functions`, and found that there are two invocations of the omnifunc function. In the wiki example, there is only one - the second invocation. Is the first invocation supposed to be handled by this plugin as well?

I have found that adding `vim.api.nvim_call_function('vimtex#complete#omnifunc',{1, ''})` triggers the completion menu, but only when prefixing whatever is typed with '\' (so typing '\beg' triggers the completion menu, but not when typing 'beg').

**Comment by dfangx** [comment]
Was wondering if there was anything regarding the two invocations I mentioned above that could be used as a proper solution to this problem?
