### ISSUE TITLE
Clangd Doesn't Give Any Completion if Snippet Support is set to true

### ISSUE THREAD

**Issue by saadparwaiz1** [nvim-lua/completion-nvim#312]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue
```
vim.g.completion_enable_snippet = 'snippets.nvim'
local lspconfig = require "lspconfig"
local snippets = require "snippets"
local completion = require("completion")

local on_attach=function(client, bufnr)
  completion.on_attach(client, bufnr)

  vim.api.nvim_command("setlocal omnifunc=v:lua.vim.lsp.omnifunc")

  vim.api.nvim_set_keymap('n', 'S', sign, options)
  vim.api.nvim_set_keymap("n", "gq", fmt, options)
  vim.api.nvim_set_keymap("n", "gd", defi, options)
  vim.api.nvim_set_keymap("n", "gr", refe, options)
  vim.api.nvim_set_keymap("n", "K", hover, options)
  vim.api.nvim_set_keymap('n', 'gD', impli, options)
  vim.api.nvim_set_keymap('n', 'gW', wrkspc, options)
  vim.api.nvim_set_keymap("n", "<Left>", pdiag, options)
  vim.api.nvim_set_keymap("n", "<Right>", ndiag, options)
end


local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

lspconfig.pyright.setup {
    on_attach = on_attach,
    cmd = {node_modules .. "pyright-langserver", '--stdio'},
    capabilities = capabilities
}

lspconfig.clangd.setup{
  capabilities = capabilities,
  on_attach = on_attach,
}
```

**How to reproduce**
Install clangd, enable snippet support in server config and completion-nvim
The current behaviour is  as follows:
![Screenshot 2020-12-29 at 11 57 13](https://user-images.githubusercontent.com/73385353/103282261-1d157180-49cd-11eb-8e62-191f045f7bb4.jpg)

If I comment out the capability line the suggestions start showing up 
![Screenshot 2020-12-29 at 11 57 48](https://user-images.githubusercontent.com/73385353/103282327-50580080-49cd-11eb-8b3a-8e749759f2fb.jpg)

**Expected behavior**
Completion Suggestion to Show up

**Comment by haorenW1025** [comment]
It works fine on my side though, but my setting is
```
lsp.clangd.setup{
  on_attach = on_attach;
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = true
        }
      }
    }
  },
}
```

**Comment by saadparwaiz1** [comment]
Ah, Interesting I'll investigate this a bit more! Thank you for your help
