### ISSUE TITLE
Using digits to select completion-nvim candidates

### ISSUE THREAD

**Issue by FelipeLema** [nvim-lua/completion-nvim#316]
**Is your feature request related to a problem? Please describe.**
Avoids pressing `<tab>` N times instead of pressing a single (digit) key. Think [`vim-easymotion`](https://github.com/easymotion/vim-easymotion) but with a narrowed, specific use within the completion window/buffer.

**Describe the solution you'd like**
Each visible candidate must have a digit assigned. Pressing a digit key will select the candidate. If pressing a digit is ambiguous between  "selecting a candidate by digit" and "inputing candidate filter string" (think inputting "a0" when candidates are "a01", "a02", "a03"...), then the latter must be selected.

I don't mind if this implementation doesn't make it to main branch. A code snippet (that can be added to my init.lua) suffices.

**Describe alternatives you've considered**
This is best described (and inspired on) [this blog post](https://oremacs.com/2017/12/27/company-numbers/). It presents an elisp implementation for Emacs + company mode.

**Comment by lithammer** [comment]
This is probably a feature request for Vim/Neovim itself since completion-nvim is just using native functionality. See `:help complete()`, `:help ins-completion` and `:help ins-completion-menu` for more info.

**Comment by FelipeLema** [comment]
thanks for your quick response.

gimme a few days to take a look at the docs for a proper reply

**Comment by haorenW1025** [comment]
Just like @lithammer said, `completion-nvim` relies on the default completion in vim cores. Although the post is a quite interesting way of doing completion I highly doubt that it'll work in vim because of the limitation of `ins-complete` base on my experience. Anyway this is out of the scope of `completion-nvim`, maybe discussing in neovim's gitter and see if anyone is interested is a better way.

**Comment by FelipeLema** [comment]
I could only find incomplete bits here and there.

According to [this stackexchange answer](https://vi.stackexchange.com/questions/12882/how-to-select-a-matched-autocompletion-item), digit keys can be mapped when doing completion. However, it does not explain how to add the corresponding index to each candidate being shown.

I'm leaving the code posted there over here for posterity (mind the license of this code follows that of stackoverflow)

```vimscript
" map 1-9 to nth item
" map shift+{1-9} to last nth item
let s:shiftKeys = '!@#$%^&*('
for s:i in range(1, 9)
  exe printf('inoremap <expr> %d pumvisible() ? <sid>select_pum(%d - 1) : %d ', s:i, s:i, s:i)
  let skey = s:shiftKeys[s:i-1]
  exe printf('inoremap <expr> %s pumvisible() ? <sid>select_pum(-%d) : "%s" ', skey, s:i, skey)
endfor

" map 0 to original item
inoremap <expr> 0 pumvisible() ? '<c-e>' : 0

function! s:select_pum(index)
  let compInfo = complete_info()
  let idx = a:index >= 0 ? a:index : a:index + len(compInfo.items)
  let d = idx - compInfo.selected
  return repeat( d > 0 ? "\<c-n>" : "\<c-p>", abs(d))
endfunction
```
Thanks, everyone... will probably ask in neovim's gitter
