### ISSUE TITLE
[Question] How can I exclude duplicate completion candidates?

### ISSUE THREAD

**Issue by nabezokodaikon** [nvim-lua/completion-nvim#318]
<img width="297" alt="スクリーンショット 2021-01-06 0 42 40" src="https://user-images.githubusercontent.com/3197942/103666547-1f249500-4fb8-11eb-877e-c849b08d8066.png">

I think it can be done by changing `dup` to` 0` in custom completion source, but I don't know how to specify LSP in custom completion source.

**Comment by haorenW1025** [comment]
I think we don't provide this for now, but maybe I can add an option for that.

**Comment by haorenW1025** [comment]
Can you try #326 and see if it works for you?

**Comment by nabezokodaikon** [comment]
Thank you for your reply.
Duplicates have been excluded in the #326  settings.

**Comment by haorenW1025** [comment]
Merged!

**Comment by nabezokodaikon** [comment]
confirmed. Thank you!
