### ISSUE TITLE
Option to sort certain completion items at the bottom (or at the top) of the list

### ISSUE THREAD

**Issue by quantum-booty** [nvim-lua/completion-nvim#329]
![image](https://user-images.githubusercontent.com/28958399/104601187-d59c1000-5671-11eb-9961-72a4369608a2.png)
Pyright language server provides dunder methods of a class, which hides the other more important items like functions and class attributes. Can we add an option to sort items so they are at the bottom? Maybe let us use regex to define things we want at the top or at the bottom.

**Comment by lithammer** [comment]
GH-234 should solve this. You can apply the diff and play around with it. But basically, it should sort completion items in the order that the language server (i.e. Pyright) wants them.

**Comment by quantum-booty** [comment]
@lithammer Thank you, this works very well :)

**Comment by haorenW1025** [comment]
@lithammer Thanks a lot for the fixes. I mainly use your code snippets in the PR so it should be working fine now.
