### ISSUE TITLE
Can't integrate with vimtex

### ISSUE THREAD

**Issue by seblj** [nvim-lua/completion-nvim#341]
I am having trouble integrating completion-nvim with vimtex even after doing exactly as said in wiki on integrating custom sources.

Neovim version: NVIM v0.5.0-dev+1045-g24b60322a
nvim-lspconfig version: 6a33e9b
completion-nvim version: fc9b2fd
vimtex version: b2e93e1

```vim
call plug#begin('~/.config/nvim/plugged') 
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
    Plug 'lervag/vimtex'
call plug#end()

autocmd BufEnter * lua require'completion'.on_attach()
lua require'lspconfig'.texlab.setup{}
lua require'completion'.addCompletionSource('vimtex', require'vimtex'.complete_item)
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

let g:completion_chain_complete_list = {
            \ 'tex' : [
            \     {'complete_items': ['vimtex']}, 
            \   ],
            \ }

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

I have configured the vimtex.lua file inside ~/.config/nvim/lua btw

**How to reproduce**
Setup vimtex as the wiki explains

**Expected behavior**
Expecting to get completion from vimtex without pressing ctrl+x, ctrl+o

**Comment by dfangx** [comment]
I had this issue too. I don't know if this is a good workaround, but I got my configuration working by adding `vim.api.nvim_call_function('vimtex#complete#omnifunc',{1, ''})` in vimtex.lua before `local items = ...`
