### ISSUE TITLE
I have to pass `snippetSupport = true` to rust-analyzer for snippets to work

### ISSUE THREAD

**Issue by emi2k01** [nvim-lua/completion-nvim#344]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue

```
call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
call plug#end()

set shortmess+=c
set completeopt=menuone,noinsert,noselect

let g:completion_enable_snippet = 'vim-vsnip'

lua <<EOF
    require'lspconfig'.rust_analyzer.setup{
        capabilities = {
            textDocument = {
                completion = {
                    completionItem = {
                        snippetSupport = true
                    }
                }
            }
        },
        on_attach=require'completion'.on_attach
    }
EOF
```

**How to reproduce**
In the function main of a cargo project type `prin`, select `print!` from the list and press enter. The snippet will be completed.

Now remove the capabilities object from the minimal init.vim file so it looks like this:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
call plug#end()

set shortmess+=c
set completeopt=menuone,noinsert,noselect

let g:completion_enable_snippet = 'vim-vsnip'

lua <<EOF
    require'lspconfig'.rust_analyzer.setup{
        on_attach=require'completion'.on_attach
    }
EOF
```

Now snippets won't work.

**Expected behavior**
Snippets should work without specifying the capability.

I was able to reproduce this with `snippets.nvim` too

NVIM v0.5.0-dev+1073-gb894fbcbe

Tried with the latest version and the git master version of rust analyzer.

Sorry if this is not a bug but it took me a while to make snippets work because this was not documented.

**Comment by lithammer** [comment]
Duplicate of https://github.com/nvim-lua/completion-nvim/issues/258

**Comment by emi2k01** [comment]
Sorry about that
