### ISSUE TITLE
[Question] how to add more than one source to snippets?

### ISSUE THREAD

**Issue by AltamimiYasser** [nvim-lua/completion-nvim#346]
I don't know if it is possible, I searched all over the docs. I tried:
`let g:completion_enable_snippet = ['UltiSnips', 'vim-vsnip']` 
and this obviously shows an error, also tried
```lua
let g:completion_enable_snippet = 'UltiSnips'
let g:completion_enable_snippet = 'vim-vsnip'
````
also didn't work, and tried:
```lua
let g:completion_enable_snippet = 'UltiSnips'
let g:completion_enable_snippet += 'vim-vsnip'
```

and didn't work :(

**Comment by Shougo** [comment]
You should not mix snippet plugins.
It conflicts with others.

**Comment by AltamimiYasser** [comment]
I was not aware of that, thanks
