### ISSUE TITLE
Cursor jumps into floating window of function signature help

### ISSUE THREAD

**Issue by loshjawrence** [nvim-lua/completion-nvim#376]
**My testing minimal init.vim**
```
call plug#begin('~/.vim/bundle')
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
call plug#end()
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
lua require'lspconfig'.tsserver.setup{on_attach=require'completion'.on_attach}
au Filetype javascript setl omnifunc=v:lua.vim.lsp.omnifunc
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
1. Get the function signature help to pop up by typing some params in a function call site.
2. Sometimes cursor will window jump into the floating window. for me its >50% of the time so it makes function signature help unusable.
3. Can try to brute force trigger by holding `,` or holding delete on a long string of `,`
![image](https://user-images.githubusercontent.com/13598291/122481015-f3143380-cf9b-11eb-9d6f-2dd25172f8ce.png)

**Expected behavior**
The cursor should not jump into the floating window of the function signature help.

**Comment by loshjawrence** [comment]
Closing as this seems to be a neovim issue.

**Comment by mjlbach** [comment]
This is not a neovim issue, but a completion.nvim issue

**Comment by jarimayenburg** [comment]
I'm having the same issue
![Peek 2021-06-21 17-43](https://user-images.githubusercontent.com/11874892/122790165-5661d680-d2b8-11eb-942a-4c0f74b22baf.gif)
