### ISSUE TITLE
ability to set the max size of the completion menu

### ISSUE THREAD

**Issue by crypticC0der** [nvim-lua/completion-nvim#390]
**Is your feature request related to a problem? Please describe.**
the completion menu whe the number of options is large can take up the entire nvim window and it can hinder usability

**Describe the solution you'd like**
ideally there would be an option to set the max line height of the menu

**Describe alternatives you've considered**
ive looked all around and cant seem to find it implemented anywhere

**Comment by Shougo** [comment]
`set pumheight=20`
