### ISSUE TITLE
Mix ins-completion sources with complete_item sources

### ISSUE THREAD

**Issue by dhazel** [nvim-lua/completion-nvim#88]
**Is your feature request related to a problem? Please describe.**
When using [omnisharp](https://github.com/OmniSharp/omnisharp-vim), I would like to have completions that include both snippets and omni completion in the same completion menu.

**Describe the solution you'd like**

	let g:completion_chain_complete_list = {
	    \'default' : [
	    \	{'complete_items': ['snippet', {'mode': 'omni'}]},
	    \]
	}

**Describe alternatives you've considered**
I have tried putting the completion sources in separate chains, but this adds extra keystrokes to access them.

	let g:completion_chain_complete_list = {
	    \'default' : [
	    \	{'complete_items': ['snippet']},
	    \	{'mode': 'omni'},
	    \]
	}

**Comment by haorenW1025** [comment]
Oh I have a guide on creating sources from omni complete now. Check that out in wiki. Close this for now.
