### ISSUE TITLE
Vsnippets not showing, but some snippets from LSP show but cause errors.

### ISSUE THREAD

**Issue by ludwj61** [nvim-lua/completion-nvim#89]
My init.vim is here: 
https://pastebin.com/U0yCke7P

Here are my lsp settings which I require in the init:
https://pastebin.com/eXMYL7Sk

**Issue**
When trying to use vsnip as snippet manager, snippets do not show. However, some snippets show without any snippet manager installed and spit out errors. 

You may notice I have disabled snippets in the sumneko_lua LSP in my lua settings. When I enable them I get the errors I mentioned and a lot of nonsense is shown in vim:

![error](https://user-images.githubusercontent.com/42984254/83275327-fffd9380-a19c-11ea-844b-a013be0d8364.png)

**How to reproduce**
Install nvim-lsp, completion-nvim, diagnostic-nvim, vsnip, and vsnip-integ. Install sumneko_lua LSP (I also don't get snippets with pyls_ms, although I haven't noticed errors), and try to use completion in an LSP-enabled file.

**Expected behavior**
If snippets are available they should be shown, otherwise none should be available.

**Comment by haorenW1025** [comment]
1. The extra snippets: LSP may returns snippets items, and if you disable `vim-vsnip-integ`, completion-nvim will filter out the extra snippets.

2. The error when expanding snippets: I believe that if you disable `completion-nvim` and use <c-x><c-o> to trigger the completion with `for`, the error will still be exists. So I think that's an issue with neovim and I don't know how to fix it.

3. vim-vsnip doesn't show snippets: It's working fine on my side though. Have you follow the guide in vim-vsnip and create your snippets? If so, please provide it so I can try to reproduce on my side.

**Comment by ludwj61** [comment]
Thanks for the response. 

Even with vim-vsnip-integ uninstalled, though, I still get the Snippets that give errors. Completion doesn't seem to be filtering them out. The same occurs without vim-snip and vim-vsnip-integ. 
Is there anything I'm missing to get rid of the "dud" snippets?

**Comment by haorenW1025** [comment]
I've looked into a bit and it seems a bug on my side... Can you update and check if it's fixed?

**Comment by ludwj61** [comment]
Thanks! Now the troublesome snippets are hidden when nvim-vsnip-integ is disabled. 

Also I was able to get my own vsnips to show up which was just user error on my side... I had my snips in the wrong file which is pretty embarrassing.

So is there any reason to use vim-vsnip-integ anymore?

**Comment by ludwj61** [comment]
Second Update: I noticed similar errors with the lua server with no snippet plugin at all:
![dsfgsdfgh](https://user-images.githubusercontent.com/42984254/83316347-4978cd80-a1f3-11ea-9e85-1e2c07a2515d.png)

I might be wrong but perhaps this issue belongs in https://github.com/neovim/nvim-lsp ?

**Comment by haorenW1025** [comment]
> So is there any reason to use vim-vsnip-integ anymore if it just causes buggy snippets?

The buggy snippets should be a issue for neovim instead of vim-vsnip-integ though. You should report the issues in neovim's repo. 

I've been using ultisnips with sumneko_lua lsp and it works totally fine... Maybe using the latest master would help since they're actively fixing issues in upstream.

**Comment by urandom** [comment]
@haorenW1025 
Perhaps, instead of filtering out the snippets, you could use 'util.parse_snippet' to get the proper insertable text? That way we'll not miss out important completion items if a snippet engine isn't present.

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L256

**Comment by haorenW1025** [comment]
@urandom Actually I've been following that PR(thanks for the great work!), so I knew I can integrate with that. The problem is I've got a lot of issues because adding stuff in master branch and leads to incompatible issue. So I kind of wanna wait for a week or so and then add that to `completion-nvim`. Thanks for the reminder still:)

**Comment by xanderio** [comment]
I still having to problem with `vim-vsnip-integ` disable. I'm using  rust-analyser.

```lua
local lsp = require'nvim_lsp'

local on_attach_vim = function()
  require'completion'.on_attach()
  require'diagnostic'.on_attach()
end


lsp.rust_analyzer.setup{
  on_attach = on_attach_vim,
  capabilities = {
    completion = {
      completionItem = {
        snippetSupport = false
      }
    }
  }
}
```

nvim version: 91e41c857622b61adcf84f6a6af87a3f5a4d65f5
completion-nvim: b411b46f7f0bd68a4124d5be0aa263ebb4aeb091

**Comment by xanderio** [comment]
As a quick workaround i'm currently using neovim/neovim@2ca8f02a6

It looks like the 'bug' only happens when running at least neovim/neovim@5a9226c800d3075821203952da7c38626180680d

**Comment by haorenW1025** [comment]
@xanderio Do you mean the `INVALID_SERVER_JSON` or the snippets not shown correctly?

**Comment by xanderio** [comment]
the snippets not showing correctly and i'm so sorry i just realist this issue is about a different problem. Should i create a new issue about this?

**Comment by haorenW1025** [comment]
@xanderio Please open a new issues and describe the details, thanks:)

**Comment by haorenW1025** [comment]
Duplicate with #123 . Merge it there.
